### ISSUE TITLE
Using signals to terminate Node application on z/OS

### ISSUE THREAD

**Issue by matthewpwilson** [ibmruntimes/node#101]
Issue raised for discussion @joransiu @mmallick-ca

We've been investigating ways to terminate Node applications on z/OS using Unix signals. We'd like to have a way to signal an application to gracefully shutdown,  but also be able to terminate the Node runtime if the application doesn't go away by itself. 

We're currently doing the following:
- Send SIGTERM
- Wait for up to 10s
- Send SIGKILL if application hasn't termination

This gives the application an opportunity to handle SIGTERM and complete any outstanding requests before terminating.

This is based on the behaviour of several process monitors / host environments as documented here: 
https://joseoncode.com/2014/07/21/graceful-shutdown-in-node-dot-js/
pm2 also documents similar behaviour.

We'd ideally like a less destructive way of terminating the application than killing the process. However we do see a need to be able to terminate the runtime immediately if the application hasn't quiesced by itself. Ideally we'd like to ensure normal cleanup is driven too, as noted in #100 the V8 heap doesn't get cleaned up if we send SIGKILL.

**Comment by jBarz** [comment]
@matthewpwilson I believe this issue is fixed in 6.14.2.
Can you verify and close this issue?

**Comment by matthewpwilson** [comment]
@jBarz I wasn't aware of a new mechanism in 6.14.2 for terminating applications without resorting to SIGKILL - have I missed something? 
(The last part regarding cleaning up the heap might be fixed, but that's the crux of this issue as far I'm concerned)

**Comment by jBarz** [comment]
We made a fix in 6.14.2 that ensures that SIGTERM does what it is supposed to do, i.e. Terminate the application gracefully (without the 10 second delay).
So you shouldn't ever need to use SIGKILL.
If there is a test case which does require you to issue a SIGKILL (with 6.14.2), that would be a problem that we will need to look into.

**Comment by matthewpwilson** [comment]
Ah, cool.  We'll look into this and feed back - I think we do have some test cases that still require a SIGKIL with 6.14.2

**Comment by jBarz** [comment]
ok, we will keep an eye out for those issues. Closing this one because of the SIGTERM fix.
