### ISSUE TITLE
z/OS: Intermittent U4094 abend when application issues process.exit()

### ISSUE THREAD

**Issue by matthewpwilson** [ibmruntimes/node#102]
We have a test application that does http.createServer then issues process.exit(1). Approx 20-30% of the time we see a U4094 abend (reason code x'48') when the application terminates. I can supply a system dump. 

Test case:
```
var http = require('http');
var process = require('process');
//create a server object:
var server = http.createServer(function (request, response) {
  response.write('Hello ProcessExit1 World! PID:' + process.pid); //write a response to the client
  response.end(); //end the response
});
process.exit(1);

process.on('SIGTERM', function () {
	  server.close(function () {
		console.log('Received SIGTERM at ' + (new Date()));
	  });
	});

console.log("Started hello.js at " + (new Date()))
server.listen(28225);
```

**Comment by jBarz** [comment]
I will look into this. A system dump would help.

**Comment by jBarz** [comment]
fyi, I have tried running this script in a loop for about 30 mins and haven't gotten an abend.
I was running under a USS env.
It might be that the abend is only reproducible in a CICS env.

**Comment by jBarz** [comment]
fyi, I ran this script in a loop for over an hour using node 6.12.3 under USS and am not able to reproduce the abend. So a system dump would definitely be useful.

**Comment by jBarz** [comment]
Got system dump offline

**Comment by jBarz** [comment]
Which version of node is being used?

**Comment by jBarz** [comment]
The system dump showed possibly that the abend occured because we were freeing a system resource while it was still being used.
I provided a test binary that closes all threads to ensure this doesn't happen

**Comment by matthewpwilson** [comment]
Looks good with the test binary @jBarz supplied.

**Comment by jBarz** [comment]
v6.13.1 is out which should resolve this issue.
