### ISSUE TITLE
node keeps core dumping even executing itself

### ISSUE THREAD

**Issue by polyrabbit** [ibmruntimes/node#103]
Hi, I'm using the ported `node-v6.13.0-os390-s390x` on z/OS, but it always core dumps saying:

```bash
bash-4.2$ node-v6.13.0-os390-s390x/bin/node
CEE3204S The system detected a protection exception (System Completion Code=0C4).
         From entry point _ZN4node6AssertEPA4_KPKc at compile unit offset +0000000015C3BC4E at entry offset +00000000000000D6 at address 0000000015C3BC4E.
Segmentation fault
```

This error happens even running node without any script, do you have any clue on this issue? thanks for any help!

**Comment by jBarz** [comment]
It seems like node is leaving behind system resources like queues/semaphores.
The new instances of node abend when the system resources limit has been reached.
Here is a simple script to cleanup

As a temporary workaround, use `ipcs` command to list system resources and `ipcrm` to cleanup.

You can also upgrade your version of node to the latest version (currently 6.13.0) which does a better job of system resource cleanup.

**Comment by polyrabbit** [comment]
Many thanks for the help, `ipcrm` indeed works!!!

One more question, does `node 6.13.0` handle it correctly or I still need to do the cleanup occasionally?

**Comment by jBarz** [comment]
A new version coming out this week (6.13.1) will have additional fixes for this specific issue which  improves on the prior release (6.13.0).
There are still some corner cases which leak system resources and we are working to fix those issues soon.

**Comment by polyrabbit** [comment]
Thanks, look forward to it~
