### ISSUE TITLE
Where to get Perl 5.6.x?

### ISSUE THREAD

**Issue by chadseippel** [ibmruntimes/node#105]
According to the doc (https://developer.ibm.com/node/sdk/ztp/#documentation-ztp), Perl 5.6.x or later is required. But the link given (http://www.rocketsoftware.com/zos-open-source/perl) only has 5.24. I attempted to install with 5.24 and I'm getting this error while running ./unpack.pl:

`$ ./unpack.pl
use: ./unpack.pl 3: FSUM7351 not found
use: ./unpack.pl 4: FSUM7351 not found
./unpack.pl 5: FSUM7332 syntax error: got (, expecting Newline
`
Could this error be caused by me using 5.24? If so, where can I find 5.6 or later. Thanks!

**Comment by jBarz** [comment]
It seems like `unpack.pl` is being run by the shell (`bin/sh`) instead of `perl`
Can you make sure that `perl` is in your PATH before you run `./unpack.pl` ?

**Comment by chadseippel** [comment]
Thanks. That seemed to do the trick!
