### ISSUE TITLE
SafeSubmit::submit_jcl hang when running unpack.pl

### ISSUE THREAD

**Issue by lw233** [ibmruntimes/node#106]
Hello, 

When tried to run unpack.pl on z, it always hangs at the SafeSubmit::submit_jcl without any message or error.   Checked the log on z console, the JCL is success.   Used perl -d to debug the unpack.pl and hang at the SafeSubmit::submit_jcl too.   And it hangs for both install and uninstall.

my @jcl_output = SafeSubmit::submit_jcl(@receive_jcl);

My z is z/OS V2R2 with PTF UI46658.    Have you ever seen this before?  And any advise?  Thank you!

**Comment by jBarz** [comment]
Did you download the trial version from here ?
https://developer.ibm.com/node/sdk/ztp/

If yes, did you set the following environment variable as the website suggested?
COMPILER_INSTALL_MSGCLASS

**Comment by lw233** [comment]
Yes, I download the trial version from this website.  And set the COMPILER_INSTALL_MSGCLASS to the value we always used.  The unpack.pl will hang.

**Comment by jBarz** [comment]
When it hangs, could you open another shell and do `ps -ef` to see what it is hanging on?

**Comment by lw233** [comment]
From another shell, it seems those thread was hang..

L057898     131407   16909028  - 17:11:27 ttyp0000  0:00 sub -w /tmp/36j63KnQ9t
L057898   16909028   33686354  - 17:11:26 ttyp0000  0:00 /bin/sh -c export PATH=$PATH:./oebin && sub -w /tmp/36j63KnQ9t
L057898   50463561   33686334  - 17:11:26 ttyp0000  0:00 perl ./unpack.pl -uninstall

**Comment by lw233** [comment]
The problem is the LPAR missed ISF.SISFLOAD dataset.  So can not find SDSF and the he shell was hang.   It's fixed.  Thanks for your help.
