### ISSUE TITLE
./unpack.pl error code 3,4 - z/OS 2.2

### ISSUE THREAD

**Issue by zurcjoe** [ibmruntimes/node#108]
_Encountering the following issue when running ./unpack.pl of IBM SDK for nodejs_

**Performed the following prior to issuing ./unpack.pl**

**pax -rf ibm-6.14.3.0-trial-node-v6.14.3-os390-s390x.pax.Z -x pax**

**export COMPILER_INSTALL_MSGCLASS=A
export COMPILER_INSTALL_HLQ=JCRUZ**

_Running the following command to install the C/C++ compiler - produces the following error messages?_

**./unpack.pl**

_/RPRT/zoe/nodejs/node-v6.14.3-os390-s390x:Ready ./unpack.pl            
### ./unpack.pl 5: FSUM7332 syntax error: got (, expecting Newline_                

_The following pre-req software dependencies have been performed:_

**perl --version**       
_This_ is perl 5, version 24, subversion 0 (v5.24.0) built for os390           

**python --version**   
_Python_ 2.7.13            

**bash -version**    
_GNU_ bash, version 4.3.46(51)-release (i370-ibm-openedition)             
_Copyright_ (C) 2013 Free Software Foundation, Inc.                            

**make -V** 
_make - Version z/OS Shell and Utilities v2.3_               

Please let me know the best way to identify the cause of this problem.

Thank you,

V/R

J.

**Comment by stevchen-ibm** [comment]
Hi @zurcjoe the issue is most likely due the missing /usr/bin/env on the system, can you please follow https://www.ibm.com/support/knowledgecenter/SSTRRS_6.0.0/com.ibm.nodejs.zos.v6.doc/env.htm to create it and try again?

Thanks,
Steven

**Comment by zurcjoe** [comment]
Thanks Steven, 

I will review and provide an update.

V/R,

Joe.

**Comment by zurcjoe** [comment]
Thank you, problem resolved.

**Comment by zurcjoe** [comment]
Problem resolved based on recommendation.
