### ISSUE TITLE
error running unpack.pl  - Fails on z/OS 2.3 with an 8 character userid.

### ISSUE THREAD

**Issue by davidkjackson** [ibmruntimes/node#110]
Attempting to install ZOWE. 
I have removed the unrelated comments from this thread as the problem is now resolved with the help of Stephen Chen at IBM.  Please see my final comment at the bottom of this thread as to the problem.

**Comment by joransiu** [comment]
Hi @davidkjackson : I checked my locally installed version of Rocket's Perl 5.24, and I do see File/Basename.pm under the library path.   Can you issue a `perl -V` and check the @INC paths listed in your environment?  I suspect you are missing the directory that has File/Basename.pm - Maybe you need PERL5LIB defined.   For reference, the perl module is located`/rsusr/rocket/lib/perl5/5.24.0/File/Basename.pm`

**Comment by davidkjackson** [comment]
Thanks for the reply.
I checked the directory and yes they are present:
$ ls
Basename.pm    Copy.pm        Find.pm        Path.pm        stat.pm
Compare.pm     Fetch.pm       GlobMapper.pm  Temp.pm

The Rocket instructions state:
Example directory /rsusr/rocket :  On our systems, I use the directory /u/rocket and changed the commands below accordingly.

mkdir -p /u/rocket
gzip -d perl-5.24.0_<build>.tar.gz
tar -C /u/rocket -xovf perl-5.24.0_<build>.tar
chmod -R 755 /u/rocket/bin/*
find /u/rocket/lib -type f -exec chmod 644 {} \;
 find /u/rocket/lib -type f -name '*.so' -exec chmod 755 {} \;
 cd /u/rocket/bin
./change_pwd_perl.sh
export _BPXK_AUTOCVT='ON'
export  _CEE_RUNOPTS='FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'
export _TAG_REDIR_ERR='TXT'
export _TAG_REDIR_IN='TXT'
export _TAG_REDIR_OUT='TXT'
export PATH=$PATH:/u/rocket/bin
export MANPATH=$MANPATH:/u/rocket/man/
export PERL5LIB=$PERL5LIB:/u/rocket/lib/perl5
export LIBPATH=$LIBPATH:/u/rocket/lib/perl5/5.24.0/os390/CORE

Sorry but not sure how to inspect @inc paths.
I issued
$ perl -v

This is perl 5, version 24, subversion 0 (v5.24.0) built for os390

**Comment by joransiu** [comment]
Can you show the output of `perl -V` (with a capital V) -- that will show the @INC paths...

**Comment by davidkjackson** [comment]
$ perl -V
Can't locate Config.pm in @INC (you may need to install the Config module) (@IN.
BEGIN failed--compilation aborted.

**Comment by joransiu** [comment]
@davidkjackson , can you run `echo $PERL5LIB` and confirm that it does contain `/u/rocket/lib/perl5` before you execute `perl -V`?   Are you able to access that directory with the ID you are running perl?

**Comment by joransiu** [comment]
@davidkjackson : Any luck with getting your perl installation to work?

**Comment by davidkjackson** [comment]
Sorry for the late reply.
I restarted the install to use the same dirs that Rocket themself recommend. i.e. /usr/rocket. Reinstalled and then attempted. the node.js install again. 
I am now getting this when I run the unpack.pl. 

$ perl unpack.pl
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
copy failed at unpack.pl line 39.
$ 

I am not sure what is being copied. The contents the uss.images directory contains this:
njsc                             File
njsc.cfg                         File
njsc++                           File
private                          Dir
run                              File
util                             Dir
xlclang                          File
xlclang++                        File
xmits                            Dir

**Comment by stevchen-ibm** [comment]
@davidkjackson 
For the error that you are getting:
```
$ perl unpack.pl
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
cp: FSUMF171 cp/mv of link "/u/node.js/node-v6.14.4-os390-s390x/uss.images/util.
copy failed at unpack.pl line 39.
```
That was because the previous installation was partial and incomplete, please try to run unpack.pl -uninstall first to clean up the previous install and then do the unpack.pl again.

**Comment by davidkjackson** [comment]
Thanks Steven - running uninstall then attempting the install again did help get past that problem.
Unfortunately, I am now getting this:

$ perl unpack.pl -uninstall
<DEB> deleting nodejs.ZOSV221.D170810.BINDER.LOAD
<DEB> cannot delete nodejs.ZOSV221.D170810.BINDER.LOAD -- has it already been d?
<DEB> deleting nodejs.ZOSV221.D170810.SCNJCMP
<DEB> cannot delete nodejs.ZOSV221.D170810.SCNJCMP -- has it already been delet?
<INFO> uninstallation complete!
$ perl unpack.pl
**<DEB> unloading /u/node.js/node-v6.14.4-os390-s390x/bin/xmits/USRHLQ.ZOSV221.D1D
An error occurred while receiving temporary dataset DJACKSON.TMP.T9893241.T4406.
<ERR> cannot receive /u/node.js/node-v6.14.4-os390-s390x/bin/xmits/USRHLQ.ZOSV2.**
$ 

I followed the node.js installation instructions and specified
$ export COMPILER_INSTALL_MSGCLASS=x
$ export COMPILER_INSTALL_HLQ=nodejs
I do notice that the Nodejs installation instructions do say that the above error can occur if the MSGCLASS has not been specified. I did as can be seen here:
$ echo $COMPILER_INSTALL_MSGCLASS
x
$

**Comment by davidkjackson** [comment]
Any idea as to how to debug and trace this unpack.pl script so I can try to work out why it is failing?

**Comment by stevchen-ibm** [comment]
@davidkjackson can you please send me an email at stevchen@ca.ibm.com? I can send you an updated perl module with more diagnostics to try it out.

**Comment by davidkjackson** [comment]
Thanks to Stephen Chen at IBM for assisting with this problem.
After running a diagnostic version of the code, it confirmed the problem.
**I am running on z/OS 2.3 and I am using a full 8 character userid.**  As a result, the unpack.pl code was attempting to append an extra character on the jobcard resulting in a 9 character Jobid.  This obviously resulted in a JCL error.  The diagnostics included the Job number so it was easy to then see the problem. Stephen provided a fixed version of unpack.pl and all is now working fine and the install completed successfully.
