### ISSUE TITLE
Assertion failed: timeout != -1, file: ../deps/uv/src/unix/os390.c, line: 888, function: uv__io_poll

### ISSUE THREAD

**Issue by lw233** [ibmruntimes/node#111]
My app runs on Z with the nodejs SDK on zos. I got error as below and my app was down,  do you have any idea on this? Thank you!

Assertion failed: timeout != -1, file: ../deps/uv/src/unix/os390.c, line: 888, function: uv__io_poll
CEE5207E The signal SIGABRT was received.

**Comment by joransiu** [comment]
@lw233, thanks for raising this issue.  Can you confirm with node version you are currently using?  i.e. `node --version` output.

I believe the assertion you are hitting is: https://github.com/ibmruntimes/node/blob/v6.x.zos/deps/uv/src/unix/os390.c#L897

**Comment by lw233** [comment]
@joransiu  The node version is v6.14.3. The package used is the free-trial version. Thank you!
