### ISSUE TITLE
unpack.pl expecting SDSF

### ISSUE THREAD

**Issue by thomas-km-liu** [ibmruntimes/node#113]
Hi,
Trying to install the C/C++ runtime and compiler that came with ibm-6.14.4.1-trial-node-v6.14.4-os390-s390x.pax.Z by running unpack.pl
Exported the 3 COMPILER environment variables per:
export COMPILER_INSTALL_MSGCLASS=V
export COMPILER_INSTALL_HLQ=SFT
export COMPILER_INSTALL_VERBOSE=1

msgclass V is an held output class.
unpack.pl issued the following 2 message and hangs:
<DEB> unloading /SYSTEM/tmp/tl/bin/xmits/USRHLQ.ZOSV221.D170810.BINDER.LOAD.XMIT into SFT.ZOSV221.D170810.BINDER.LOAD
<INFO> Running Command: '/bin/env -i /bin/sh -c 'export PATH=$PATH:./oebin && sub -w /tmp/MndMcTJyan''

Looking at the sub Rexx script in the oebin directory, it's looking for SDSF.  We don't have SDSF so it's never going to work.  Any suggestion on how to get around it, may be straight TSO STATUS & TSO OUTLIST commands?

Regards,
Thomas

**Comment by stevchen-ibm** [comment]
Hi @thomas-km-liu ,
Sorry to hear about your problem.
Unfortunately, currently unpack.pl installation does require availability of SDSF on the system (*and* the necessary access to use it as or it will hang, see issue 106 for details), which is used by the script to submit JES2 jobs and checking status of the jobs.
Please note that we do have the SMP/E version now available in shopZ with no charge. Maybe you can try that one out.
Regards,
Steven

**Comment by thomas-km-liu** [comment]
Hi Steven,
Made a few changes to oebin/sub and unpack.pl and completed the unpack process.  However, the bin/njsc.cfg used in the IVP assumed all the LE and Runtime Library Extension dataset to be have HLQ of CEE.  But ours all have HLP of SYS1.  I had to change all of the to SYS1.CEE.* & SYS1.CBC.* before the IVP would work (and the whole unpack.pl worked from beginning to end).  Might be there should be another environment variable for the HLQ for LE & RLE datasets used for the IVP.

Regards,
Thomas

**Comment by stevchen-ibm** [comment]
Hi Thomas, 
Absolutely.
This (with environment variables to replace HLQ for LE and RTE) together with some other minor improvements have already been discussed and worked on for next major update of the scripts. Thanks for your feedback and glad that you have made it worked from beginning to the end now.
Regards,
Steven
