### ISSUE TITLE
z/OS Configuration page has incorrect paths for the PATH configuration statements

### ISSUE THREAD

**Issue by johnottogood** [ibmruntimes/node#117]
On the Installing and configuring page:(https://www.ibm.com/support/knowledgecenter/SSTRRS_6.0.0/com.ibm.nodejs.zos.v6.doc/install.htm)
 -under environment variables, it has this for the suggested PATH:

export PATH=$PATH:$PathPrefix/usr/lpp/nodejs/usr/lpp/IBM/cnj/IBM
/node-latest-os390-s390x/bin:$PathPrefix/usr/lpp/nodejs/usr/lpp/IBM/cnj/njsc/bin:
/rsusr/rocket/bin

It seems the "/usr/lpp/nodejs" substring for both PATH components should not be there.   The suggested PATH should be 

export PATH=$PATH:$PathPrefix/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin:$PathPrefix/usr/lpp/IBM/cnj/njsc/bin:/rsusr/rocket/bin.

Checking the Program Directory document for NodeJS for z/OS confirms my finding:
(page 23 of GI13-4703-00)
1. By default the root HFS path of SDK for Node.js is /usr/lpp/IBM/cnj, if a prefix #PathPrefix is used
during installation, please change the attributes referencing /usr/lpp/IBM/cnj to
#PathPrefix/usr/lpp/IBM/cnj

**Comment by joransiu** [comment]
Thanks @johnottogood.  You are correct.  We'll get the page updated.  Thanks for raising this issue!

**Comment by joransiu** [comment]
@johnottogood, https://www.ibm.com/support/knowledgecenter/SSTRRS_6.0.0/com.ibm.nodejs.zos.v6.doc/install.htm has now been updated with the correct PATH.  Many thanks again for pointing this out.
