### ISSUE TITLE
unpack.pl compilation aborted

### ISSUE THREAD

**Issue by lp419665** [ibmruntimes/node#120]
I'm getting compilation error in unpack.pl script:

A013129:/shared/nodejs/node-v6.16.0-os390-s390x: >perl unpack.pl
Can't locate File/Basename.pm in @INC (you may need to install the File::Basename module) (@INC contains: /rsusr/rocket/lib/perl5/site_perl/5.24.0/os390 /rsusr/rocket/lib/perl5/site_perl/5.24.0 /rsusr/rocket/lib/perl5/5.24.0/os390 /rsusr/rocket/lib/perl5/5.24.0 .) at unpack.pl line 3.
BEGIN failed--compilation aborted at unpack.pl line 3.

Perl version:

A013129:/shared/nodejs/node-v6.16.0-os390-s390x: >perl -v
This is perl 5, version 24, subversion 0 (v5.24.0) built for os390

**Comment by joransiu** [comment]
@lp419665 : This looks like a configuration issue with your perl installation.  Can you confirm if `Basename.pm` is found within `/rsusr/rocket/lib/perl5/5.24.0/File`?  That's where it's found on my installation.

**Comment by lp419665** [comment]
Thank you. I sorted it out. It was issue with Perl installation.
