### ISSUE TITLE
Error installing Node: "CEE3501S Module CXXRT64 was not found"

### ISSUE THREAD

**Issue by mrmikopi** [ibmruntimes/node#128]
* **Version**: v8.16.0
* **Platform**: UNIX on z/OS 2.2
* **Subsystem**:

While trying to install Node.js on z/OS 2.2, we encountered an error with code CEE3501S. Node is required for Zowe. I guess there are some PTFs but they are for zOS 2.3, as far as i know. 

That would be great if there is a workaround instead of PTFs, otherwise it would be really hard for our working site.

**Comment by joransiu** [comment]
Hi @mrmikopi, the pre-requisite PTFs for V2.2 are documented under: https://www.ibm.com/support/knowledgecenter/SSTRRS_8.0.0/com.ibm.nodejs.zos.v8.doc/smpe.htm

The missing CXXRT64 does seem to imply you are missing the pre-req LE PTF.  We unfortunately do not ship that LE library to STEPLIB to.  Any chance you can get the PTFs applied?

**Comment by mrmikopi** [comment]
Business site is available to apply PTFs, but it will take a long time until that happens. That's why we were seeking any workarounds. 
Thanks for your help.

**Comment by Rajeckum** [comment]
I encountered the similar issue and once I got the PTFs applied, it has been resolved.
