### ISSUE TITLE
S0C4 Abend

### ISSUE THREAD

**Issue by Rajeckum** [ibmruntimes/node#137]
>npm init
CEE3204S The system detected a protection exception (System Completion Code=0C4).
         From compile unit TLBA99ME:/home/jenkins/workspace/ibmnode-8.x-zos-build/node/deps/v8z/src/heap/spaces.cc at entry point v8::internal::MemoryChunk::Initialize(v8::internal::Heap*, unsigned char*, unsigned long, u... at statement 555 at compile
         unit offset +00000000337858F4 at entry offset +0000000000000044 at address 00000000337858F4.

LEAID201I - LEAID64 ENTERED (LEVEL 12/05/2016 12.37 PTF-PT00159).
LEAID207I - LEAID64 RETURN FROM ABEND-AID, RC=0.
[1] + Done(139) npm init
  33620741      Segmentation violation  /usr/lpp/node-v6.14.4-os390-s390x/bin/npm

>node dsclean.js
CEE3204S The system detected a protection exception (System Completion Code=0C4).
         From compile unit TLBA99ME:/home/jenkins/workspace/ibmnode-8.x-zos-build/node/deps/v8z/src/heap/spaces.cc at entry point v8::internal::MemoryChunk::Initialize(v8::internal::Heap*, unsigned char*, unsigned long, u... at statement 555 at compile
         unit offset +00000000337858F4 at entry offset +0000000000000044 at address 00000000337858F4.

LEAID201I - LEAID64 ENTERED (LEVEL 12/05/2016 12.37 PTF-PT00159).
LEAID207I - LEAID64 RETURN FROM ABEND-AID, RC=0.

[1] + Done(139) node dsclean.js
  67175173      Segmentation violation  /usr/lpp/node-v6.14.4-os390-s390x/bin/node

* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by Rajeckum** [comment]
As per IBM reference in https://www.ibm.com/support/knowledgecenter/en/SSTRRS_6.0.0/com.ibm.nodejs.zos.v6.doc/troubleshoot.htm, I've cleared semaphores with ipcrm command. It works for first time and then again it gets abended with S0C4. 

Kindly advise.

**Comment by IgorTodorovskiIBM** [comment]
Hi Rajeckum,

It seems that you are not on the latest PTF level of Version 6.    Please see https://www.ibm.com/support/pages/fix-list-ibm-sdk-nodejs-zos for the latest fixes.   The latest level is 6.17.   

If possible, I would recommend that you upgrade to IBM SDK for Node.js - z/OS, Version 8 - Available here: https://www.ibm.com/us-en/marketplace/sdk-nodejs-compiler-zos/purchase

**Comment by IgorTodorovskiIBM** [comment]
Can you also confirm if you're using Node 6.14.4 as the path may not indicate the true version:
`node --version`

Can you also let us know what OS/arch you are using:
`uname -a`

**Comment by Rajeckum** [comment]
node --version ------------> v8.16.0                  
uname -a -------------> OS/390 MSYS 25.00 04 2964

**Comment by IgorTodorovskiIBM** [comment]
Hi, can you set this environment variable: `export __MEM_ACCOUNT=1` and rerun and post your output.  Thanks

**Comment by Rajeckum** [comment]
Hi Igor,

Thanks for the advise. Here is the output. 

/usr/lpp/node-v6.14.4-os390-s390x/bin: >export __MEM_ACCOUNT=1   
/usr/lpp/node-v6.14.4-os390-s390x/bin: >npm -v                   
__iarv64_alloc: pid 50397721 tid 1 ptr=7FFFF000 size=536870912 rc=8             
ADDED:@50082f79d0 size 536870912 RMODE64                                        
__iarv64_alloc: pid 50397721 tid 1 ptr=A2200000 size=1048576 rc=0               
ADDED:@a2200000 size 1048576 RMODE64                                            
__iarv64_alloc: pid 50397721 tid 1 ptr=A2300000 size=1048576 rc=0               
ADDED:@a2300000 size 1048576 RMODE64                                            
ADDED: @36ebe000 size 49152                                                     
CEE3204S The system detected a protection exception (System Completion Code=0C4)
.                                                                               
         From compile unit TLBA99ME:/home/jenkins/workspace/ibmnode-8.x-zos-buil
d/node/deps/v8z/src/heap/spaces.cc at entry point v8::internal::MemoryChunk::Ini
tialize(v8::internal::Heap*, unsigned char*, unsigned long, u... at statement 55
5 at compile                                                                    
         unit offset +0000000033F278F4 at entry offset +0000000000000044 at addr
ess 0000000033F278F4.                                                           
LEAID201I - LEAID64 ENTERED (LEVEL 12/05/2016 12.37 PTF-PT00159).               
LEAID207I - LEAID64 RETURN FROM ABEND-AID, RC=0.                                
Ý1¨ + Done(139) npm -v                                                          
  50397721      Segmentation violation  ./npm

**Comment by Rajeckum** [comment]
Hi Igor,

Any advise?

Thanks,
Rajesh Kumar C

**Comment by IgorTodorovskiIBM** [comment]
@Rajeckum , please verify if this is still an issue.  We have made updates since v8.16.0 which address how memory allocation is handled.
