### ISSUE TITLE
npm commands throwing error - FSUM7332 syntax error: got), expecting Newline

### ISSUE THREAD

**Issue by kashifzowe** [ibmruntimes/node#138]
* **8.16.0**:
* **OS/390**:
* **Subsystem**:

Hi,
I have installed an evaluation version of Node.js on Mainframe (z/OS USS). When I run the command node --version I get a good output. However, when I run npm --version I get the error 
FSUM7332 syntax error: got), expecting Newline

I would appreciate any help here...

Thank you.

**Comment by IgorTodorovskiIBM** [comment]
Hi,

You will need the following environment variables (as described here: https://rtpdoc01.rtp.raleigh.ibm.com:9443/kc/SSTRRS_8.0.0/com.ibm.nodejs.zos.v8.doc/paxz.htm)
```
export _BPXK_AUTOCVT=ON
export _CEE_RUNOPTS="FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
```

**Comment by gireeshpunathil** [comment]
for me, the link is not accessible.

**Comment by richardlau** [comment]
I think https://www.ibm.com/support/knowledgecenter/SSTRRS_8.0.0/com.ibm.nodejs.zos.v8.doc/paxz.htm is the correct link.

**Comment by IgorTodorovskiIBM** [comment]
@kashifzowe , is this still an issue for you?
