### ISSUE TITLE
Unexpected autoencoding behavior of v8.16.1

### ISSUE THREAD

**Issue by DNikolaevAtRocket** [ibmruntimes/node#142]
* **Version**:  8.16.1
* **Platform**: OS/390 SS01 26.00 04 3906
* **Subsystem**: n/a

v8.16.1 performs auto-encoding depending on file tags not in a way it is done in previous versions.
Regardless of which way is more reasonable, it's a breaking change which is not expected in a micro release.

Please see the table below.

| File tag \ NodeJS version | v6.17 | v8.16.0  |  v8.16.1 |
| --------------------- |:------:| ---------:|--------:|
| untagged                  | auto-encoding    | auto-encoding | **no auto-encoding**        |
| binary                       |  no auto-encoding|  no auto-encoding| no auto-encoding|
| mixed                       |  auto-encoding|  auto-encoding| **no auto-encoding**        |
| text IBM1047           | auto-encoding| auto-encoding| auto-encoding|
| text ISO8859-1        | no auto-encoding| no auto-encoding| no auto-encoding|
| text UTF-8                | auto-encoding| auto-encoding| **no auto-encoding**       |

**Comment by IgorTodorovskiIBM** [comment]
Hi, we introduced an environment variable to control auto-conversion for untagged files.  We made this change after GA to address untagged repositories that contain ebcdic and binary data.  Previous behaviour did not allow this.   
```
__UNTAGGED_READ_MODE: 
Set to "DEFAULT" for handling of reading untagged files, up to 4k of data will be read and checked, if it is found to be in ccsid 1047, convert data from ccsid 1047 to ccsid 819. 
Set to "WARN" for same behavior as DEFAULT but issue a warning if conversion occurs. 
Set to "V6" for same behavior as node v6, i.e. always convert data from ccsid 1047 to ccsid 819.  
Set to "STRICT" for no explicit conversion of data
```
Can you try to set `export __UNTAGGED_READ_MODE=V6`.

Do you have a specific example of what is currently breaking?

Their may be an issue with the heuristic used in the DEFAULT mode.

**Comment by DNikolaevAtRocket** [comment]
Hi @IgorTodorovskiIBM,

Thank you for the response, the variable worked.
We'll be back with examples later.

@1000TurquoisePogs, 
Is the examples something you could help with?

**Comment by Joe-Winchester** [comment]
@dmitrynikolaev - is the problem you see that all of the graphics disappear and also apps like TN3270 fail to load, ... 
![image](https://user-images.githubusercontent.com/28100302/67026511-c7beae80-f0ff-11e9-99f1-e78a475e8a45.png)

**Comment by Joe-Winchester** [comment]
@IgorTodorovskiIBM - do you have a build that is post GA that works if the `export __UNTAGGED_READ_MODE=V6` is set ?  If so I'd be happy to test that and also we could update the `run-zowe.sh` script to do the export

**Comment by DNikolaevAtRocket** [comment]
@Joe-Winchester,
That's correct.

**Comment by IgorTodorovskiIBM** [comment]
Yes, you can download ibm-8.16.1a-os390-s390x.pax.Z  (288 MB)   from here: https://www.ibm.com/ca-en/marketplace/sdk-nodejs-compiler-zos

**Comment by IgorTodorovskiIBM** [comment]
I made the GA v8.16.0 available as well

**Comment by DNikolaevAtRocket** [comment]
Thank you @IgorTodorovskiIBM

**Comment by Joe-Winchester** [comment]
Tks @IgorTodorovskiIBM - how long will this link be available ?  Can we put it in the zowe docs for our release ?

**Comment by IgorTodorovskiIBM** [comment]
We're in the processing of building another PTF for Node v8, so we can look at potentially fixing this issue or worst case, reverting to export __UNTAGGED_READ_MODE=V6 if it works.

**Comment by IgorTodorovskiIBM** [comment]
> Tks @IgorTodorovskiIBM - how long will this link be available ? Can we put it in the zowe docs for our release ?

Yes, it should be available indefinitely

**Comment by IgorTodorovskiIBM** [comment]
If `export __UNTAGGED_READ_MODE=V6` works, then you should be able to modify your run-zowe.sh for all Node versions to include that envar.  You will get the same behaviour.  I would recommend that approach since we do have some memory related fixes in the Node v8 PTFs.  

Another solution would be to tag your untagged files using the chtag command.  
`chtag -tc 1047 <filename>` or `chtag -tc binary <filename>` and then when generating the pax file, make sure you preserve the file tags.

**Comment by IgorTodorovskiIBM** [comment]
After some discussion, we decided that we will revert __UNTAGGED_READ_MODE to V6 in the next Node v8 PTF.  We also noticed an issue with our current implementation of  __UNTAGGED_READ_MODE=V6, where it is converting both untagged and tagged files from 1047 to ASCII.  We plan to address this in the next PTF.   Right now I would recommend that customers use Node v8.16.0 until the next PTF is issued.

**Comment by Joe-Winchester** [comment]
Are you going to pull 8.16.1 from the site until your PTF is out ?  

I agree we should tag everything as you suggest to avoid any untagged file, but this is going to take us some time to get right and test and have our .pax build preserve, ...

We are doing a mod to our Zowe 1.6 build to do the `export __UNTAGGED_READ_MODE=v6` as you suggest however older builds without this will fail with 8.16.1.

**Comment by IgorTodorovskiIBM** [comment]
v8.16.1 has an additional memory leak fix that affected some clients.  We will push for a PTF release for early next week.

**Comment by ehrocha** [comment]
FYI,I have tried adding export __UNTAGGED_READ_MODE=V6 to the run-zowe.sh, did not work with the 8.16.1a version . Still not drawing assets correctly .

**Comment by IgorTodorovskiIBM** [comment]
Do you have a zowe log with the Node.js error?  The screenshot reveals a FE or UI issue, but no details on the Node.js issue.

@dmitrynikolaev, you mentioned the `export __UNTAGGED_READ_MODE=V6` setting worked.  In what context?

I noticed a few of the untagged Javascript files in the Zowe 1.5.0 distribution contain a mix of EBCDIC and Unicode data. 

For example: `./zlux-server-framework/node_modules/iconv-lite/encodings/sbcs-data.js`

Here's the entire list of files that do not contain valid ebcdic data:
```
./zlux-server-framework/node_modules/iconv-lite/encodings/sbcs-data.js
./zlux-server-framework/node_modules/iconv-lite/encodings/sbcs-data-generated.js
./zlux-server-framework/node_modules/validator/lib/alpha.js
./sample-react-app/web/assets/i18n/i18n.js
./sample-react-app/webClient/src/assets/i18n/i18n.js
./zlux-editor/web/assets/monaco/vs/language/html/htmlWorker.js
./zlux-editor/web/assets/monaco/vs/editor/editor.main.nls.zh-tw.js
./zlux-editor/web/assets/monaco/vs/editor/editor.main.nls.ru.js
./zlux-editor/web/assets/monaco/vs/editor/editor.main.nls.zh-cn.js
./zlux-editor/web/assets/monaco/vs/editor/editor.main.nls.ko.js
./zlux-editor/web/assets/monaco/vs/editor/editor.main.nls.fr.js
./zlux-editor/web/assets/monaco/vs/editor/editor.main.nls.ja.js
```

Most of these javascript files are from downloaded npms and original ASCII.  Unfortunately, Node v6 automatically converted downloaded npms from UTF8 to EBCDIC forcefully, and in some cases the conversion is not valid.   In Node v8, an` npm install` or `npm reinstall` will tag the files as ASCII and no conversion is necessary.  I recommend for future releases that you perform an `npm reinstall` and ship the ASCII tagged node_module files.

**Comment by Joe-Winchester** [comment]
> FYI,I have tried adding export __UNTAGGED_READ_MODE=V6 to the run-zowe.sh, did not work with the 8.16.1a version . Still not drawing assets correctly .

Where did you add the line ?  I created a branch where it was included at line 93 and it seemed to work OK for our automation and manual tests.  https://github.com/zowe/zowe-install-packaging/blob/rc/scripts/run-zowe.template.sh.

**Comment by DNikolaevAtRocket** [comment]
@IgorTodorovskiIBM 

> Do you have a zowe log with the Node.js error? The screenshot reveals a FE or UI issue, but no details on the Node.js issue.

There's nothing particular in Zowe log; NodeJS server serves the files as usually, but the encoding is wrong which we can see only on client (browser) side. 
@1000TurquoisePogs, can you please provide technical details on the NodeJS side of the problem?

> I noticed a few of the untagged Javascript files in the Zowe 1.5.0 distribution contain a mix of EBCDIC and Unicode data.

We don't build this part of Zowe on Z for a number of reasons, 
It's being built on a distributed system, then **everything** gets converted to EBCDIC during packaging; no tagging is performed.

**Comment by IgorTodorovskiIBM** [comment]
Just a warning, if you start introducing node.js native npm dependencies (C/C++ npms) such as the bcrypt npm to zowe, then building on a distributed system may be an issue as there is no cross-compiler for z/OS.

Converting UTF8/ASCII encoded files to EBCDIC can potentially lead to functional issues, especially if the npm package uses Unicode symbols in strings, which is supported: https://flaviocopes.com/javascript-unicode/

My suggestion would be to forego the conversion and simply tag the node_modules directory, using `chtag -R -tc 819 node_modules/` and upon packaging, you can preserve the tags with the pax option `-o saveext `

**Comment by 1000TurquoisePogs** [comment]
@IgorTodorovskiIBM 
I took a look at how 8.16.0 & 8.16.1 behaved without setting `__UNTAGGED_READ_MODE`, and with `BPXK_AUTOCVT` on. The result of what worked is attached here. 
![image](https://user-images.githubusercontent.com/30730276/67886875-9d69e980-fb20-11e9-825e-afe24d80afae.png)

The 1047 encoding was done via PAX, which seems to handle binary-to-1047 better than FTP or iconv.
As implied, the behavior change is only about untagged files, and for text the untagged behavior is better, but for binary the untagged behavior is incompatible without setting `__UNTAGGED_READ_MODE`. 

The way we serve files over the network with Zowe is by using ExpressJS' "serve-static" https://github.com/expressjs/serve-static and a library that extends serve-static to send a gzip version of the requested file if a `.gz` file is available in the same directory: https://www.npmjs.com/package/express-static-gzip

So, this change effected Zowe for any file that had a Gzip version, and all images that were loaded over the network rather than embedded into the HTML (some images were B64 encoded into the html by Webpack)

**Comment by 1000TurquoisePogs** [comment]
Tagging files is a good idea, and we will do this.
But, @IgorTodorovskiIBM your tagging suggestions only work for files that are shipped or created manually. We need a way to tag files that the nodejs server creates at runtime. How can we do this?

We have REST apis that writes files to disk using `fs` (https://nodejs.org/api/fs.html)
It would be a very good idea to enhance `fs` or provide an IBM 3rd party library extension to `fs` that adds a `fs.chtag` and adds tagging information to `fs.stat`. Does this exist already?

**Comment by IgorTodorovskiIBM** [comment]
Thanks @1000TurquoisePogs , that is a good suggestion.  We are considering writing an npm to expose such z/OS C LE functions as chtag.   Currently, you can use exec or spawn to execute /bin/chtag. 

Eg:
```
const execSync = require('child_process').execSync;
function chtag(ccsid, filename) {
  return execSync('/bin/chtag -tc ' + ccsid + ' '  + filename);
}

chtag(1047, "bla.txt2");
```  
-----
FYI. we have released an update to Node.js - z/OS - V8, the November PTF based on v8.16.2.  This reverts the untagged behaviour back to the original V6 behaviour (convert from 1047 to ASCII for all untagged files regardless of content).  However, we do still encourage you set the __UNTAGGED_READ_MODE envar.

SMP/E PTF information:
Apar: PH18674
PTF: UI66188
 
PAX Download:
https://www.ibm.com/account/reg/ca-en/signup?formid=urx-38045

**Comment by IgorTodorovskiIBM** [comment]
@1000TurquoisePogs, @Joe-Winchester  we have created an npm (mvsutils) that exposes the GetFileCcsid and SetFileCcsid interfaces (https://www.npmjs.com/package/mvsutils).  It works on Node v8 and Node v12

**Comment by ccw-1** [comment]
You can also fix untagg text file (created by npm with node version 6, that was actually in unicode, but hard converted by a 1-1 mapping to EBCDIC),  with this:
__UNTAGGED_READ_MODE=v6 node -e "require('fs').createReadStream('old.js').pipe(require('fs').createWriteStream('new.js'))"

**Comment by IgorTodorovskiIBM** [comment]
Solution was provided, closing issue
