### ISSUE TITLE
ZOWE Started Task fails to connect to server using Node.js

### ISSUE THREAD

**Issue by TerriMenchak** [ibmruntimes/node#157]
**Client Concerns/Problem**
(Node.js V12, z.OS V2.2, ZOWE V1.7.0) After starting up the ZOWESVR subsystem for ZOWE, the customer sees error messages in the ZOWE started task output that seem to be related to Node.js.

Error 0: Could not contact z/OS MF on 'https://nag4.bhsbx.ibm.com:3443/zosmf/info';; -
Error 2: Could not contact z/OS MF on 'https://nag4.bhsbx.ibm.com:3443/zosmf/info';; -

There is a ZOSE script that is validating the connectivity to 
https://nag4.bhsbx.ibm.com:3443/zosmf/info by executing Node.js.  It appears
that the return code is something other than the expected RC=200.

When the script is executed manually through OMVS, it works and gets RC=200.
When the script is executed through ZOWE using Node.js, it fails.

**Files**
The files are located on the MCEVS1 z/OS system.  They cannot be attached to Github as that is in violation of GDPR.  (They can, however, be moved to TOROLABW, if that is helpful.  Let me know if you need this.)
To access the files on MCEVS1, you must have an Ecurep userid and click this link, before trying to access the files on MCEVS1:
https://ecurep.mainz.de.ibm.com/ae5/#id=TS003256341&path=TS003256341%2F0-all_data%2F&filepath=TS003256341%2F0-all_data%2FZOSMF_VALIDATE.txt 

SF.T00325.S6341.NODESERV.ASCII - NODE SERVER Log

SF.T00325.S6341.ZOSMF.VALIDATE
-- The ZOWE script (/scripts/utils/validate-zosmf-host-and-port.sh) that generates
   the errors seen in the next file.

SF.T00325.S6341.ZOWESVR.OUTPUT 
-- ZOWESVR started task joblog & output
-- Error messages can be seen here.
   Error 0: Could not contact z/OS MF on 'https://nag4.bhsbx.ibm.com:3443/zosmf/info';;; -
   Error 2: Could not contact z/OS MF on 'https://nag4.bhsbx.ibm.com:3443/zosmf/info';;; -

SF.T00325.S6341.ZOWE - I am not sure yet exactly what this file is that the customer sent   

This is the text that the customer wrote in the Salesforce case TS003256341:
=========================================================
Hi team,

We are running z/OS V2R2 on a Z13 Hardware. We've been facing some issues while installing Zowe 1.7.0 in our mainframe environment, and we believe Node.js may have something to do with the errors. We would like you to review this case and tell us if Node.js can be the reason.

First, we requested Node.js to be installed on our system since it is a prerequisite for the Zowe. Node.js 12 was installed. After executing the Zowe installation/configuration scripts and setting the RACF accesses properly, we started the ZOWESVR subsystem. During the startup, we saw some error messages that might be related to Node.js, as you can see in the task output .(See file SF.T00325.S6341.ZOWESVR.OUTPUT.)

The first error message we can see in the output is:

Error 0: Could not contact z/OS MF on 'https://nag4.bhsbx.ibm.com:3443/zosmf/info'; -
Error 2: Could not contact z/OS MF on 'https://nag4.bhsbx.ibm.com:3443/zosmf/info'; -

I tracked down the step in Zowe scripts and found /scripts/utils/validate-zosmf-host-and-port.sh. (See file SF.T00325.S6341.ZOSMF.VALIDATE.)

I see this script is validating the connectivity to https://nag4.bhsbx.ibm.com:3443/zosmf/info by executing Node.js:

RESPONSE_CODE=`node ${ROOT_DIR}/scripts/utils/zosmfHttpRequest.js ${ZOSMF_HOST} ${ZOSMF_PORT}`

The link can be accessed via web browser without any issues. 
As per the script logic, the error message I mentioned is printed when the Node.js command receives a RESPONSE_CODE different than 200.

To perform a test, I executed the script in OMVS manually, and received RESPONSE_CODE=200. However, when the validation is executed through the Zowe scripts, it receives something else, which is not even readable, and prints the error message.

To help you in this investigation, I have also sent the NodeServer log.  (See file SF.T00325.S6341.NODESERV.ASCII.)

This error message I mentioned is just one of them. You can find other error messages in the started task output, specially during the NodeServer startup.

Please, advise if possible.

Thanks in advance,
RODOLFO FERRAZ NOGUEIRA - IBM
=========================================================

You assistance is appreciated.  You can message me directly in Slack at @TerriMenchak .
 
Thanks,
Terri Menchak

**Comment by IgorTodorovskiIBM** [comment]
Based on your description, particularly, "it receives something else, which is not even readable, and prints the error message."
I suspect an encoding issue, you likely need to set these environment variables:
```
export _TAG_REDIR_IN=txt
export _TAG_REDIR_ERR=txt
export _TAG_REDIR_OUT=txt
```
in the `/scripts/utils/validate-zosmf-host-and-port.sh` script.

I believe the Zowe team was making changes in this regard.  Kathy Chan was looking into it.

**Comment by 1000TurquoisePogs** [comment]
I think this one can be closed, because zowe did not support node v12 until version 1.9, which includes those environment variables by default. It should work these days.
