### ISSUE TITLE
process.title and --title don't do anything

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [ibmruntimes/node#163]
Version: 6.17.0, 8.16.2, and 12.16.1
Platform: z/OS 2.4
Subsystem: process

For Zowe, I'm looking to have the process name match the component name, as seen in https://github.com/zowe/zlux-server-framework/pull/188 and https://github.com/zowe/zlux-app-server/pull/109
Apparently `--title` on the command line is an option, but only was introduced in v10, and seems to not work on 12.16.1
So, I wanted to use `process.title` in the code instead, which should exist on every version of node.
When I use this, no exception is thrown but also no change in behavior happens. The process title remains unchanged.

Also, note that process.title has had issues with certain node versions on linux, too. It had issues on 8.10, but worked perfectly for me on 6.13.1 and 12.16.1... hope that helps to isolate the problem.

**Comment by IgorTodorovskiIBM** [comment]
Unfortunately, setproctitle is not implemented on z/OS.   One alternative is to use or generate a symbolic link `ln -s node zowe-node` and invoke `zowe-node`.

**Comment by 1000TurquoisePogs** [comment]
Thank you. That's an interesting alternative. I would really like & hope that z/OS does support this ability some day, but understand that's not at the node level so closing for now.
