### ISSUE TITLE
nodejs(version 0.10.25) runs on AIX OS: TypeError: Object has no method 'isSymbolicLink'

### ISSUE THREAD

**Issue by xhappy** [ibmruntimes/node#28]
Compiled successfully in AIX machine using IBM XL C/C++ compiler. and the command "node -v“ run successfully.

but an error happened when run an simple test case, the details is as following.
content of script example print.js:
console.log('hello world');
using the command: node print.js, the error messages are as following:

fs.js:1267
if (!stat.isSymbolicLink()) {
^
TypeError: Object has no method 'isSymbolicLink'
at Object.realpathSync (fs.js:1267:17)
at tryFile (module.js:142:15)
at Function.Module._findPath (module.js:181:18)
at Function.Module._resolveFilename (module.js:336:25)
at Function.Module._load (module.js:280:25)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:902:3

This issue occurs in the fs.js file, the codes are following:
fs.realpathSync = function realpathSync(p, cache) {
// make p is absolute
p = pathModule.resolve(p);

if (cache && Object.prototype.hasOwnProperty.call(cache, p)) {
return cache[p];
}

var original = p,
seenLinks = {},
knownHard = {};

// current character position in p
var pos;
// the partial path so far, including a trailing slash if any
var current;
// the partial path without a trailing slash (except when pointing at a root)
var base;
// the partial path scanned in the previous round, with slash
var previous;

start();

function start() {
// Skip over roots
var m = splitRootRe.exec(p);
pos = m[0].length;
current = m[0];
base = m[0];
previous = '';

// On windows, check that the root exists. On unix there is no need.
if (isWindows && !knownHard[base]) {
  fs.lstatSync(base);
  knownHard[base] = true;
}
}

// walk down the path, swapping out linked pathparts for their real
// values
// NB: p.length changes.
while (pos < p.length) {
// find the next part
nextPartRe.lastIndex = pos;
var result = nextPartRe.exec(p);
previous = current;
current += result[0];
base = previous + result[1];
pos = nextPartRe.lastIndex;

// continue if not a symlink
if (knownHard[base] || (cache && cache[base] === base)) {
  continue;
}

var resolvedLink;
if (cache && Object.prototype.hasOwnProperty.call(cache, base)) {
  // some known symbolic link.  no need to stat again.
  resolvedLink = cache[base];
} else {
  var stat = fs.lstatSync(base);
  if (!stat.isSymbolicLink()) {   //Error occurred!!!!!
    knownHard[base] = true;
    if (cache) cache[base] = base;
    continue;
  }

  // read the link if it wasn't read before
  // dev/ino always return 0 on windows, so skip the check.
  var linkTarget = null;
  if (!isWindows) {
    var id = stat.dev.toString(32) + ':' + stat.ino.toString(32);
    if (seenLinks.hasOwnProperty(id)) {
      linkTarget = seenLinks[id];
    }
  }
  if (linkTarget === null) {
    fs.statSync(base);
    linkTarget = fs.readlinkSync(base);
  }
  resolvedLink = pathModule.resolve(previous, linkTarget);
  // track this, if given a cache.
  if (cache) cache[base] = resolvedLink;
  if (!isWindows) seenLinks[id] = linkTarget;
}

// resolve the link, then start over
p = pathModule.resolve(resolvedLink, p.slice(pos));
start();
}

if (cache) cache[original] = p;

return p;
};

I have investigate the issue a long time, but I have no idea how to solve it.

who can help me?

**Comment by joransiu** [comment]
Just cleaning through old issues.  We and the Node.js community are still using GCC to build Node.js on AIX.... The XL C/C++ issues may still persist, but it's not a priority atm.    @xhappy, if this is still a concern for you, please reopen the issue, and we can explore next steps.
