### ISSUE TITLE
Compilation problem on AIX 6.1: sys/ahafs_evProds.h: No such file or directory

### ISSUE THREAD

**Issue by andreasalin** [ibmruntimes/node#32]
I would be very happy if someone has a solution for my compilation problem. Thank you in advance.

My configuration:
gcc version 4.4.5
GNU Make 3.8.2
AIX 6.1

While compiling node-0.10.26-release-ppc I get the following error lines:
////////////////////////////////
../deps/uv/src/unix/aix.c:59:31: warning: sys/ahafs_evProds.h: No such file or directory
../deps/uv/src/unix/aix.c: In function 'setup_ahafs':
../deps/uv/src/unix/aix.c:671: warning: passing argument 1 of 'file_is_a_directory' discards qualifiers from pointer target type
../deps/uv/src/unix/aix.c:523: note: expected 'char _' but argument is of type 'const char *'
../deps/uv/src/unix/aix.c:685: warning: passing argument 1 of 'mk_subdirs' discards qualifiers from pointer target type
../deps/uv/src/unix/aix.c:629: note: expected 'char *' but argument is of type 'const char *'
../deps/uv/src/unix/aix.c: In function 'parse_data':
../deps/uv/src/unix/aix.c:798: error: 'AHAFS_MODDIR_UNMOUNT' undeclared (first use in this function)
../deps/uv/src/unix/aix.c:798: error: (Each undeclared identifier is reported only once
../deps/uv/src/unix/aix.c:798: error: for each function it appears in.)
../deps/uv/src/unix/aix.c:798: error: 'AHAFS_MODDIR_REMOVE_SELF' undeclared (first use in this function)
../deps/uv/src/unix/aix.c:812: warning: passing argument 1 of 'strdup' from incompatible pointer type
/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/4.4.5/include-fixed/string.h:210: note: expected 'const char *' but argument is of type 'char (_)[1023]'
../deps/uv/src/unix/aix.c:817: error: 'AHAFS_MODFILE_RENAME' undeclared (first use in this function)
../deps/uv/src/unix/aix.c: In function 'uv__ahafs_event':
../deps/uv/src/unix/aix.c:866: warning: comparison between pointer and integer
../deps/uv/src/unix/aix.c:877: warning: comparison between pointer and integer
../deps/uv/src/unix/aix.c:889: warning: passing argument 2 of 'handle->cb' from incompatible pointer type
../deps/uv/src/unix/aix.c:889: note: expected 'const char _' but argument is of type 'char (_)[1023]'
../deps/uv/src/unix/aix.c: In function 'uv_fs_event_init':
../deps/uv/src/unix/aix.c:940: warning: comparison between pointer and integer
../deps/uv/src/unix/aix.c:960: warning: passing argument 1 of 'strdup' from incompatible pointer type
/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/4.4.5/include-fixed/string.h:210: note: expected 'const char _' but argument is of type 'char (_)[1023]'
../deps/uv/src/unix/aix.c: In function 'uv__fs_event_close':
../deps/uv/src/unix/aix.c:973: warning: 'return' with a value, in function returning void
../deps/uv/src/unix/aix.c:989: warning: 'return' with a value, in function returning void
make[1]: **\* [/opt/mcrm/devel/user/alin/temp/node_js/node-0.10.26-release-ppc/out/Release/obj.target/libuv/deps/uv/src/unix/aix.o] Error 1
make[1]: Leaving directory `/opt/mcrm/devel/user/alin/temp/node_js/node-0.10.26-release-ppc/out'
make: **\* [node] Error 2
//////////////////////////////////

I think the problems occur since bos.ahafs is not installed and therefore the header file /usr/include/sys/ahafs_evProds.h is not existing, right? 

$ lslpp -f bos.ahafs
lslpp: Fileset bos.ahafs not installed.

Unfortunately I think there is no way to install bos.ahafs on the AIX machine by our clients it-departement so I have to find a another way? I would be happy if anyone has a fix or even a suggestion.

**Comment by joransiu** [comment]
This issue should be fixed by @gireeshpunathil referenced PR above.   I see from the code now that `sys/ahafs_evProds.h` include is guarded by `#ifdef HAVE_SYS_AHAFS_EVPRODS_H` [1].  Closing the issue.

[1] https://github.com/libuv/libuv/blob/v1.x/src/unix/aix.c#L55-L57

**Comment by scottrpoulin** [comment]
If AIX doesn't have sys/ahafs_evProds.h
it won't be able to execute uv__fs_event_close, thus libuv make check will fail?
