### ISSUE TITLE
node.js on a WD My Book Live Duo

### ISSUE THREAD

**Issue by matths** [ibmruntimes/node#55]
Hi Andrew,
it's not an issue, but more of a question. I have this My Book Live Duo (Software Raid) running a Debian Linux. I would like to know, what steps I would need to do, to install / compile node.js
I think, it's also a PowerPC architecture wise as /proc/cpuinfo states the following:

```
processor   : 0
cpu     : APM82181
clock       : 800.000008MHz
revision    : 28.131 (pvr 12c4 1c83)
bogomips    : 1600.00
timebase    : 800000008
platform    : PowerPC 44x Platform
model       : amcc,apollo3g
Memory      : 256 MB
```

I am not that familiar with cross-compiling, so I guess I could compile stuff directly on the device, if there's no binary version I could give a try.
Any advice or recommendation is welcome.

Best regards,
Matthias

**Comment by andrewlow** [comment]
This is likely to hit the same problems we've seen with the freescale processors https://github.com/andrewlow/v8ppc/issues/99 - I'm only guessing based on it being a NAS.

1st step would be to get v8 working on the machine 1st, so head over there and see if you can get that going.

**Comment by hansschl** [comment]
Hi, I also want to run node on a WD MyBook Live.
I tried downloading a recent node package for PPC 603 from Optware, and also tried to compile the sources with gcc from Optware, but without success: keep getting "Illegal instruction" errors.
Has anyone here had more success? Any hints would be great!

**Comment by andrewlow** [comment]
@hansschl hmm.. "WD MyBook Live" reportedly uses an Applied Micro APM82181 CPU

https://en.wikipedia.org/wiki/Western_Digital_My_Book#My_Book_Live

This looks like a version of the PPC 400 instruction set. I strongly suspect it suffers from the same problem of lack of FPU instructions (implemented in the same manner as the code expects). While this CPU probably does have FPU instructions, it probably doesn't have FPU registers and re-uses the integer registers. This is normally done with a different set of FPU instructions -- and thus the incompatibility with this code base arises.

Making this, and other embedded versions of the PPC work is a project we continue to hope someone in the community will step up to do.

**Comment by hansschl** [comment]
Andrew, thanks a lot for your comments!
I will have to move to another hardware instead of porting Node to this one.
One problem with this "WD MyBook Live" NAS is that it is quite dated, and such a port would probably not have many actual users.
Thanks again!

**Comment by andrewlow** [comment]
If you're just looking for a cheap (embedded) option to run Node, look at the RaspberryPi - it's a full ARM platform which is well supported by Node.js 

There are even reasonable NAS setups for the Pi http://www.techradar.com/how-to/computing/how-to-build-your-own-raspberry-pi-nas-1315968

Many commercial NAS systems will use 'weird' CPUs making software compatibility tricky. There apparently are Intel based NAS systems out there, that'd probably be the safest bet for easy software portability. (QNAP TS-251 seems like one choice there)
