### ISSUE TITLE
Would this ever run on a PPC e500 chip?

### ISSUE THREAD

**Issue by Antic5** [ibmruntimes/node#67]
The reason I ask is there at a ton of us left out in the cold on Synology boxes... 

Freescale QorIQ  to be exact.

https://global.download.synology.com/download/Document/DataSheet/DiskStation/13-year/DS213+/Synology_DS213+_Data_Sheet_enu.pdf

**Comment by mhdawson** [comment]
See https://github.com/ibmruntimes/node/issues/9 and related issues. It all comes down to whether somebody has the skills/time to contribute support for the required instructions to the v8 PPC port.

**Comment by Antic5** [comment]
Makes sense, thanks for chiming in here!

**Comment by mhdawson** [comment]
Going to close, please re-open if you disagree.
