### ISSUE TITLE
Port the two V8 commits in Node.js v0.10.47 to deps/v8ppc

### ISSUE THREAD

**Issue by richardlau** [ibmruntimes/node#68]
v0.10.47 contained two V8 commits that were ported to `deps/v8z` in the `v0.10-ppc` branch. These should also be ported to `deps/v8ppc` for the Power platforms.

CC @BethGriggs @sxa555

**Comment by BethGriggs** [comment]
Do you mean these two commits? 
https://github.com/ibmruntimes/node/commit/ca2913e9ddd1300a53654288d3269a4cb21c3dd4
https://github.com/ibmruntimes/node/commit/0e5506525df8d1782505c9b7d235ebaf4435cb28

**Comment by BethGriggs** [comment]
The two commits have now been ported - see https://github.com/ibmruntimes/node/commits/v0.10-ppc/deps/v8ppc.

**Comment by richardlau** [comment]
Yes, those were the two commits. Thanks. :+1:
