### ISSUE TITLE
npm on z/OS has incorrect location for node

### ISSUE THREAD

**Issue by crshnburn** [ibmruntimes/node#69]
Running npm on z/OS gives the following error `npm 2: FSUM7332 syntax error: got (), expecting Word`

this is because the npm script has the following line as the location of the node runtime
```sh
#!/home/jenkins/workspace/ibmnode-ascii-v0.12-build-zos/install/bin/node
```
Editting this file to make the first line
```sh
#!/usr/bin/env node
```
allows the npm command to run as expected (providing that `node` is on the path)

**Comment by jBarz** [comment]
We are able to reproduce the issue.

Using the following environment variable during build seems to fix this.
export PORTABLE=1
This should be fixed in the next update

**Comment by richardlau** [comment]
`PORTABLE=1` is automatically set if you build the [`binary` target](https://github.com/ibmruntimes/node/blob/v0.12-zos-ascii/Makefile#L502) (the `binary` target is used on the other platforms to produce the `tar.gz` package).

**Comment by jBarz** [comment]
The binary has been updated with the fix. Please re-do all installation steps with the new binary.
Closing this item
