### ISSUE TITLE
npm install -g strongloop give cb() never called! error on z/OS

### ISSUE THREAD

**Issue by smartmouse** [ibmruntimes/node#70]
/u/slbld>npm install -g strongloop
npm ERR! cb() never called!
:/u/slbld>node -v
v0.12.17
:/u/slbld>npm -v
2.15.1

machine: slbld@zoscan2d

This is a blocking issue for trying out strongloop.

**Comment by joransiu** [comment]
@smartmouse : Does reissuing the npm command work?   `cb() never called` can show up if a connection is dropped, and is a well known issue: https://github.com/npm/npm/issues/2907

**Comment by smartmouse** [comment]
no does not work

**Comment by jBarz** [comment]
For the case in [npm/npm#2907](https://github.com/npm/npm/issues/2907) they say that it was a temporary network problem that resulted in corrupt downloads.
I am unable to reproduce the problem on our machines. So I am guessing that the network issue is probably resolved. 
@smartmouse: If you still see network issues, the workaround suggested in #2907 is the following:
npm install npm-install-retry
npm-install-retry --wait 500 --attempts 10 strongloop

**Comment by smartmouse** [comment]
I retried tonight - regardless of some errors, it seems that slc was installed
However, there are some garbage strings in the help

:/u/slbld>slc -v
strongloop v6.0.3 (node v0.12.17)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.1 (b51fc45)
├── generator-loopback@1.24.5 (de24875)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

:/u/slbld>slc --help
usage: slc <-h|--help|-v|--version>
usage: slc <command> [--help] [...]

Command-line tool for development and control of a Node application.

Options:
  -h,--help     Print usage for slc, or for an slc command, and exit.
  -v,--version  Print versions of slc and its dependencies, and exit.

Commands:

  arc: StrongLoop GUI, an alternative to the CLI

    Launch the StrongLoop GUI, a graphical alternative to the `loopback`,
    `build`, `deploy`, and `ctl` commands, that also offers run-time
    profiling and debugging.

  loopback: LoopBack application scaffolder

    Create LoopBack 2.x applications, datasources, models, ACLs, and relations.

  debug: Node.js application debugger

  start: start a node application under a local process manager

    Start a local process manager, if necessary, and run the application
    in-place.

  build: package a node application for deployment

    Packages a node application as an npm tarball or into a git deploy branch.
    Deploy the package using the `deploy` command, or your existing DevOps
    pipeline.

  deploy: deploy a node application package

    Deploy an application to the StrongLoop process manager (see `pm-install`
    command), or to any PaaS that can accept a `git push` of a node
    application.

  ctl: control a node application hosted by the process manager

    Run-time remote control of clustering, profiling, logging, restart, etc.
    See the `pm-install` and `pm` commands.

  pm-install: install the StrongLoop process manager

    The process manager hosts applications, allowing them to be deployed,
    re-deployed, controlled, and monitored, and for application metrics and
    logs to be viewed in Arc and published to thirdparty services (Splunk,
    Datadog, Statsd, etc.). To experiment locally with the manager without
    installing, see the `pm` command.


These commands are used internally, and may be useful when building custom
tooling and integrations with StrongLoop features:

  pm: ru?@???@⣙???Ӗ??@???????@???????@@@@Ֆ??????k@???@???????@???????@??@?????????@??@?@??????@???????@M???????@??@@@@???????]@???@???@??@???@??????k@???@??@???@??@???@????????@???@@@@???????????????k@??@??@?????@??????@ą?֗?@??????????@???????K@@???z@?????????@?@????@???????????@@@@㈅@⣙???Ӗ??@??????k@???@??????????@???????@?@????@???????????@????@@@@????@??????????k@?????????k@???????@??????????@???@????????k@???????@@@@?????????k@???????k@???K@Ֆ??????k@???@????@??@???@???????@???????k@???@@@@??@???@??@???@????????@???@???????????????k@??@??@?????@??????@ą?֗?@@@@??????????@???????K@@??????z@???????@?@????@???????????@??????@??@???@??????????@@@@䢅???@????@?????@???@y???y@???????@????????K@@????????z@???@????????@????????????@@@@⦉???@???????@???@??????????@???@???????@????????@???????@????K@䢅???@@@@??@?@?????????@??@ą?֗?a??@?????????k@??@????@???@???????@????K:/u/slbld>

**Comment by smartmouse** [comment]
The  above is a new unrelated issue and we have opened a new issue to track the garbage display.
The original cb() issue is due to the network instability and now it is gone. We can close this.

**Comment by smartmouse** [comment]
despite of many errors in the install

erros in install
https://gist.github.com/smartmouse/057a1a4395ac8d1aeef8ead6efcc7bae

0, strong-trace-waterfalldata@1.0.1, strong-mesh-client@1.6.3)
:/u/slbld>slc -v
strongloop v6.0.3 (node v0.12.17)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.1 (b51fc45)
├── generator-loopback@1.25.0 (6a0e2c0)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

:/u/slbld>
