### ISSUE TITLE
npm install -g loopback-connector-soap  issues

### ISSUE THREAD

**Issue by smartmouse** [ibmruntimes/node#71]
:/u/slbld>npm install -g loopback-connector-soap
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.12.17","npm":"2.15.1"})
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN engine xmlbuilder@8.2.2: wanted: {"node":">=4.0"} (current: {"node":"0.12.17","npm":"2.15.1"})
\
> ursa@0.9.4 install /u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
make: execvp: g++: EDC5111I Permission denied.
ursaNative.target.mk:97: recipe for target 'Release/obj.target/ursaNative/src/ursaNative.o' failed
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 127
make: Leaving directory '/u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Öâaóùð òôKðð
gyp ERR! command "node" "/u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa
gyp ERR! node -v v0.12.17
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional dep failed, continuing ursa@0.9.4
loopback-connector-soap@3.0.1 /u/slbld/node/lib/node_modules/loopback-connector-soap
├── debug@2.3.3 (ms@0.7.2)
├── request@2.79.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, oauth-sign@0.8.2, forever-agent@0.6.1, tunnel-agent@0.4.3, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, aws4@1.5.0, uuid@3.0.1, combined-stream@1.0.5, qs@6.3.0, mime-types@2.1.13, form-data@2.1.2, tough-cookie@2.3.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── strong-soap@1.0.2 (compress@0.99.0, optional@0.1.3, sax@1.2.1, node-uuid@1.4.7, xmlbuilder@8.2.2, xml-crypto@0.8.4, path@0.12.7, selectn@1.1.1, lodash@4.17.2)
└── strong-globalize@2.8.0 (optional@0.1.3, word-count@0.2.2, xtend@4.0.1, estraverse@4.2.0, posix-getopt@1.2.0, md5@2.2.1, mktmpdir@0.1.1, async@1.5.2, os-locale@1.4.0, esprima@2.7.3, mkdirp@0.5.1, htmlparser2@3.9.2, fs-sync@1.0.3, yamljs@0.2.8, g11n-pipeline@1.2.3, lodash@4.17.2)
:/u/slbld>

environment: slbld@zoscan2d.canlab.ibm.com
:/u/slbld>npm -v
2.15.1
n:/u/slbld>node -v
v0.12.17

**Comment by joransiu** [comment]
This looks like it's trying to compile native add-ons with g++, instead of xlC?
> make: execvp: g++: EDC5111I Permission denied

**Comment by jBarz** [comment]
use these environment flags
export CC=/bin/xlc
export CXX=/bin/xlC

**Comment by joransiu** [comment]
@smartmouse, can you set the `CC` and `CXX` environment variables as @jBarz suggested, and confirm whether the issue is resolved in your environment?

**Comment by smartmouse** [comment]
```
:/u/slbld>source .profile
/u/slbld>tail .profile
export TERM=dtterm
export CC=/bin/xlc
export CXX=/bin/xlC
:/u/slbld>npm install -g loopback-connector-soap
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.12.17","npm":"2.15.1"})
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN engine xmlbuilder@8.2.2: wanted: {"node":">=4.0"} (current: {"node":"0.12.17","npm":"2.15.1"})
-
> ursa@0.9.4 install /u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa
> node-gyp rebuild

�������?>��/������ˌ�������ˌ��>������CEE5207E The signal SIGABRT was received.
npm WARN optional dep failed, continuing ursa@0.9.4

```

**Comment by jBarz** [comment]
This issue occured because the system ran out of resources (semaphores).
The following command will clear up the resources.
``for u in `ipcs | grep "^s.*$(whoami)" | tr -s ' ' | cut -d' ' -f2`; do ipcrm -s $u; done``

**Comment by smartmouse** [comment]
:/u/slbld>for u in `ipcs | grep "^s.*$(whoami)" | tr -s ' ' | cut -d' ' -f2`; d
o ipcrm -s $u; done
:/u/slbld>npm install -g loopback-connector-soap
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.12.17","npm":"2.15.1"})
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN engine xmlbuilder@8.2.2: wanted: {"node":">=4.0"} (current: {"node":"0.12.17","npm":"2.15.1"})
 
> ursa@0.9.4 install /u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
CCN0465(W) "MAKEDEP" requires at most "0" sub-option(s) to be specified. "1" were given.
"../node_modules/nan/nan_implementation_12_inl.h", line 127.61: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan_implementation_12_inl.h", line 99.59: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1926.50: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1931.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, Local<v8::Value>, const PropertyCallbackInfo<void> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1969.50: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1978.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, Local<v8::Value>, const PropertyCallbackInfo<void> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2027.50: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2032.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, Local<v8::Value>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2038.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Integer> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2044.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Boolean> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2050.52: CCN5216 (W) An expression of type "void (*)(const PropertyCallbackInfo<v8::Array> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2097.50: CCN5216 (W) An expression of type "void (*)(unsigned int, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2102.52: CCN5216 (W) An expression of type "void (*)(unsigned int, Local<v8::Value>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2108.52: CCN5216 (W) An expression of type "void (*)(unsigned int, const PropertyCallbackInfo<v8::Integer> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2114.52: CCN5216 (W) An expression of type "void (*)(unsigned int, const PropertyCallbackInfo<v8::Boolean> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2120.52: CCN5216 (W) An expression of type "void (*)(const PropertyCallbackInfo<v8::Array> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2153.50: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2175.50: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"/u/slbld/.node-gyp/0.12.17/include/node/uv.h", line 1488.16: CCN6410 (W) The function "uv_tty_set_mode" specified in "pragma export" is not uniquely identified. The pragma is ignored.
  SOLINK_MODULE(target) Release/obj.target/ursaNative.node
 IEW2456E 9207 SYMBOL __dl__Q2_3NanEI20EscapableHandleScopeFPvUl UNRESOLVED.    
          MEMBER COULD NOT BE INCLUDED FROM THE DESIGNATED CALL LIBRARY.        
 IEW2456E 9207 SYMBOL __dl__Q2_3NanEI11HandleScopeFPvUl UNRESOLVED.  MEMBER     
          COULD NOT BE INCLUDED FROM THE DESIGNATED CALL LIBRARY.               
FSUM3065 The LINKEDIT step ended with return code 8.
ursaNative.target.mk:123: recipe for target 'Release/obj.target/ursaNative.node' failed
make: *** [Release/obj.target/ursaNative.node] Error 3
make: Leaving directory '/u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Öâaóùð òôKðð
gyp ERR! command "node" "/u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa
gyp ERR! node -v v0.12.17
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing ursa@0.9.4
loopback-connector-soap@3.0.1 /u/slbld/node/lib/node_modules/loopback-connector-soap
├── debug@2.3.3 (ms@0.7.2)
├── request@2.79.0 (is-typedarray@1.0.0, oauth-sign@0.8.2, aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.3, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, aws4@1.5.0, uuid@3.0.1, qs@6.3.0, combined-stream@1.0.5, form-data@2.1.2, mime-types@2.1.13, tough-cookie@2.3.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── strong-soap@1.0.2 (compress@0.99.0, optional@0.1.3, sax@1.2.1, node-uuid@1.4.7, xmlbuilder@8.2.2, xml-crypto@0.8.4, path@0.12.7, selectn@1.1.1, lodash@4.17.2)
└── strong-globalize@2.8.0 (optional@0.1.3, xtend@4.0.1, word-count@0.2.2, estraverse@4.2.0, posix-getopt@1.2.0, async@1.5.2, esprima@2.7.3, md5@2.2.1, mktmpdir@0.1.1, mkdirp@0.5.1, os-locale@1.4.0, htmlparser2@3.9.2, fs-sync@1.0.3, yamljs@0.2.8, lodash@4.17.2, g11n-pipeline@1.2.3)
:/u/slbld>

**Comment by smartmouse** [comment]
should we increase the memory of the system? We have not done much so far.
How much memory do you have in the development machine.?

**Comment by jBarz** [comment]
The above issue is due to a compiler limitation when compiling the _nan_ headers. We are trying to get this fixed by the compiler team.

I have forked the nan project with a workaround here.
https://github.com/jBarz/nan/tree/v2.3.3.zos

before doing 
npm install loopback-connector-soap

do this
npm install https://github.com/jBarz/nan/tarball/v2.3.3.zos

**Comment by smartmouse** [comment]
:/u/slbld>npm install -g  https://github.com/jBarz/nan/tarball/v2.3.3.zos
nan@2.3.3 /u/slbld/node/lib/node_modules/nan
:/u/slbld>npm install -g loopback-connector-soap
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.12.17","npm":"2.15.1"})
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN engine xmlbuilder@8.2.2: wanted: {"node":">=4.0"} (current: {"node":"0.12.17","npm":"2.15.1"})
-
> ursa@0.9.4 install /u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
CCN0465(W) "MAKEDEP" requires at most "0" sub-option(s) to be specified. "1" were given.
"../node_modules/nan/nan_implementation_12_inl.h", line 127.61: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan_implementation_12_inl.h", line 99.59: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1926.50: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1931.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, Local<v8::Value>, const PropertyCallbackInfo<void> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1969.50: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 1978.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, Local<v8::Value>, const PropertyCallbackInfo<void> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2027.50: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2032.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, Local<v8::Value>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2038.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Integer> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2044.52: CCN5216 (W) An expression of type "void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Boolean> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2050.52: CCN5216 (W) An expression of type "void (*)(const PropertyCallbackInfo<v8::Array> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2097.50: CCN5216 (W) An expression of type "void (*)(unsigned int, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2102.52: CCN5216 (W) An expression of type "void (*)(unsigned int, Local<v8::Value>, const PropertyCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2108.52: CCN5216 (W) An expression of type "void (*)(unsigned int, const PropertyCallbackInfo<v8::Integer> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2114.52: CCN5216 (W) An expression of type "void (*)(unsigned int, const PropertyCallbackInfo<v8::Boolean> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2120.52: CCN5216 (W) An expression of type "void (*)(const PropertyCallbackInfo<v8::Array> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2153.50: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"../node_modules/nan/nan.h", line 2175.50: CCN5216 (W) An expression of type "void (*)(const FunctionCallbackInfo<v8::Value> &)" cannot be converted to type "void *".
"/u/slbld/.node-gyp/0.12.17/include/node/uv.h", line 1488.16: CCN6410 (W) The function "uv_tty_set_mode" specified in "pragma export" is not uniquely identified. The pragma is ignored.
  SOLINK_MODULE(target) Release/obj.target/ursaNative.node
 IEW2456E 9207 SYMBOL __dl__Q2_3NanEI20EscapableHandleScopeFPvUl UNRESOLVED.    
          MEMBER COULD NOT BE INCLUDED FROM THE DESIGNATED CALL LIBRARY.        
 IEW2456E 9207 SYMBOL __dl__Q2_3NanEI11HandleScopeFPvUl UNRESOLVED.  MEMBER     
          COULD NOT BE INCLUDED FROM THE DESIGNATED CALL LIBRARY.               
FSUM3065 The LINKEDIT step ended with return code 8.
ursaNative.target.mk:123: recipe for target 'Release/obj.target/ursaNative.node' failed
make: *** [Release/obj.target/ursaNative.node] Error 3
make: Leaving directory '/u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Öâaóùð òôKðð
gyp ERR! command "node" "/u/slbld/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /u/slbld/node/lib/node_modules/loopback-connector-soap/node_modules/strong-soap/node_modules/ursa
gyp ERR! node -v v0.12.17
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing ursa@0.9.4

loopback-connector-soap@3.0.1 /u/slbld/node/lib/node_modules/loopback-connector-soap
├── debug@2.3.3 (ms@0.7.2)
├── request@2.79.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, oauth-sign@0.8.2, forever-agent@0.6.1, tunnel-agent@0.4.3, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, aws4@1.5.0, uuid@3.0.1, combined-stream@1.0.5, qs@6.3.0, form-data@2.1.2, mime-types@2.1.13, tough-cookie@2.3.2, har-validator@2.0.6, hawk@3.1.3, http-signature@1.1.1)
├── strong-soap@1.0.2 (compress@0.99.0, optional@0.1.3, sax@1.2.1, node-uuid@1.4.7, xmlbuilder@8.2.2, xml-crypto@0.8.4, path@0.12.7, selectn@1.1.1, lodash@4.17.2)
└── strong-globalize@2.8.0 (optional@0.1.3, word-count@0.2.2, xtend@4.0.1, estraverse@4.2.0, posix-getopt@1.2.0, md5@2.2.1, mktmpdir@0.1.1, async@1.5.2, os-locale@1.4.0, esprima@2.7.3, mkdirp@0.5.1, htmlparser2@3.9.2, fs-sync@1.0.3, yamljs@0.2.8, g11n-pipeline@1.2.3, lodash@4.17.2)
:/u/slbld>
:/u/slbld>


:/u/slbld>npm ls -g loopback-connector-soap
/u/slbld/node/lib
└── loopback-connector-soap@3.0.1 



still saw some optional dep build error but looks like it is installed afterall.
