### ISSUE TITLE
npm install -g loopback-connector-informix issues on z/OS

### ISSUE THREAD

**Issue by smartmouse** [ibmruntimes/node#74]
:/u/slbld>npm install -g loopback-connector-informix
\
> ibm_db@0.0.19 install /u/slbld/node/lib/node_modules/loopback-connector-informix/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/os390s390x_odbc_cli.tar.gz...
Unable to download IBM ODBC and CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/os390s390x_odbc_cli.tar.gz
npm ERR! Öâaóùð òôKðð
npm ERR! argv "/u/slbld/node/bin/node" "/u/slbld/node/bin/npm" "install" "-g" "loopback-connector-informix"
npm ERR! node v0.12.17
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.19 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@0.0.19 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /u/slbld/npm-debug.log

**Comment by joransiu** [comment]
This issue is due to lack of zOS compatible cli drivers for DB2 from the ibm_db module.  We'll touch base with the owners of ibm_db to see if they can provide z/OS support.

**Comment by bimalkjha** [comment]
@joransiu I would like to understand - you are trying to install loopback-connector on a mainframe system running z/OS or a mainframe system running Linux i.e. zLinux? ibm_db works on zLinux  and I can work to diagnose any issue, but ibm_db can not be installed on a mainframe as of now. thanks.

**Comment by gibfahn** [comment]
@bimalkjha Joran and his team are working on the [zOS port of node](https://developer.ibm.com/node/sdk/#ztp).

**Comment by joransiu** [comment]
Thanks @gibfahn.  Just to confirm, we are validating loopback-connector running on z/OS, hence we want to get ibm_db working on z/OS proper.

**Comment by joransiu** [comment]
ibm_db @ 2.4.1 supports work on z/OS using the ODBC driver support from Db2 on z/OS.
