### ISSUE TITLE
How to fix garbage display on z/OS

### ISSUE THREAD

**Issue by smartmouse** [ibmruntimes/node#75]
Sometimes when we execute commands on z/OS, we got garbage display. How to fix this?
to reproduce execute slc -h

These commands are used internally, and may be useful when building custom
tooling and integrations with StrongLoop features:

pm: ru?@???@⣙???Ӗ??@???????@???????@@@@Ֆ??????k@???@???????@???????@??@?????????@??@?@??????@???????@M???????@??@@@@???????]@???@???@??@???@??????k@???@??@???@??@???@????????@???@@@@???????????????k@??@??@?????@??????@ą?֗?@??????????@???????K@@???z@?????????@?@????@???????????@@@@㈅@⣙???Ӗ??@??????k@???@??????????@???????@?@????@???????????@????@@@@????@??????????k@?????????k@???????@??????????@???@????????k@???????@@@@?????????k@???????k@???K@Ֆ??????k@???@????@??@???@???????@???????k@???@@@@??@???@??@???@????????@???@???????????????k@??@??@?????@??????@ą?֗?@@@@??????????@???????K@@??????z@???????@?@????@???????????@??????@??@???@??????????@@@@䢅???@????@?????@???@y???y@???????@????????K@@????????z@???@????????@????????????@@@@⦉???@???????@???@??????????@???@???????@????????@???????@????K@䢅???@@@@??@?@?????????@??@ą?֗?a??@?????????k@??@????@???@???????@????K:/u/slbld>

**Comment by smartmouse** [comment]
please provide the steps to be able to view the real text. Thanks

**Comment by mmallick-ca** [comment]
pipe the output to "iconv -f ISO8859-1 -t IBM-1047" so in this case it should be
slc -h | iconv -f "ISO8859-1" -t "IBM-1047"

**Comment by jBarz** [comment]
fixed in the latest node v6.11 beta2 available for download here
https://developer.ibm.com/node/sdk/ztp/
