### ISSUE TITLE
Investigate jenkins set up on Z/OS

### ISSUE THREAD

**Issue by smartmouse** [ibmruntimes/node#76]
Once the manual trial is done and most issues are fixed, and the driver is more stable.
We can have the jenkin running the lists of loopback-connectors from jenkins.

**Comment by jBarz** [comment]
Since this is not a node runtimes issue so I will close it.
We can track this internally via RTC.

**Comment by joransiu** [comment]
Agreed with @jBarz.   @smartmouse: This issue probably makes more sense to be tracked by StrongLoop, as that's an integration issue related to your CI.
