### ISSUE TITLE
npm install -g strongloop has some nan errors on Z/OS

### ISSUE THREAD

**Issue by smartmouse** [ibmruntimes/node#77]

**Comment by jBarz** [comment]
I am working on upstreaming some changes to nan and getting approval.
In the meanwhile, use the following npm option to install any package with nan dependency.
--link https://github.com/jBarz/nan/tarball/master

**Comment by jBarz** [comment]
the changes have been committed
https://github.com/nodejs/nan/commit/0fe38215ff8581703967dfd26c12793feb960018
The next npm release of "nan" should work fine

**Comment by jBarz** [comment]
@smartmouse :
New "nan" is available as v2.5.0
So the strongloop packages and dependencies will need to upgrade to using 2.5.0

**Comment by sam-github** [comment]
Hopefully all strongloop packages are depending on `nan@^2`, so the latest nan will release will be picked up by them automatically.

**Comment by jBarz** [comment]
The node-sqlite3 package requires `nan: ~2.4.0`
I could submit a PR to change that to 2.5.0

**Comment by sam-github** [comment]
To `^2.5.0` (or you'll have to PR it over, and over, and over...), but yeah, three thumbs up for PRing it.
