### ISSUE TITLE
Investigate how to set up db2 for zOS

### ISSUE THREAD

**Issue by smartmouse** [ibmruntimes/node#78]
Pre-req for loopback-connector-db2 for z/OS

**Comment by joransiu** [comment]
@smartmouse: This issue probably makes more sense to be tracked by StrongLoop.  Setting up DB2 is not related to the node runtime, and is something you need to work out with your sysprogs.  

On the other hand, we will, of course, look into issues with npm modules, and work with respective module owners, if issues arise. 

I'm going to close this issue.
