### ISSUE TITLE
Getting an "Illegal Instruction" error when trying to run z/OS node command

### ISSUE THREAD

**Issue by Kevchuck** [ibmruntimes/node#79]
After installing the z/OS node technical preview, when running a node -v command or node -h command, those run fine.  However when I try to run node by itself, I get an Illegal Instruction error.

Download used: http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?popup=Y&la_formnum=&li_formnum=L-PIVN-AG7G3Q&title=IBM%20SDK%20for%20Node.js%20z/OS%20Technical%20Preview&accepted_url=http://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/nodejs/1.2.0.16ea3/os390/s390x/ibm-1.2.0.16-ea3-node-v0.12.17-os390-s390x.pax.Z

Instructions for installation: https://developer.ibm.com/node/sdk/#ztp

Error message: 
������/�/����?ʀ�>���/������%%?�/��?>��/�%�����?���ˀ?�Ȁ?À_�_?�`����CEE3201S The system detected an operation exception (System Completion Code=0C1).
         From entry point v8::base::OS::Abort() at compile unit offset +0000000000000000 at entry offset -00000000315596B8 at address 0000000000000000.
         Possible Bad Branch:  Statement: 342  Offset: +00000032
Illegal instruction

**Comment by mmallick-ca** [comment]
Could you share the  CEEDUMP file, if its being generated, when it hits the SOC1? 

Thanks

**Comment by Kevchuck** [comment]
Here is the CEEDUMP file that was produced.
[CEEDUMP.20161207.095134.133737.zip](https://github.com/ibmruntimes/node/files/637125/CEEDUMP.20161207.095134.133737.zip)

**Comment by mmallick-ca** [comment]
At first glance it looks like V8 is unable to setup the heap are there any restrictions on the amount of memory available to node in your environment?

**Comment by Kevchuck** [comment]
What would be the best command to determine the memory utilization?  Commands like top and vmstat aren't working in the environment (not found).  In the meantime, I'll check on what the overall setup is for the environment.  What is the minimum recommended?

**Comment by mmallick-ca** [comment]
"ulimit -a" will list the current settings. Our test system configuration is listed below:
core file           8192b
cpu time          unlimited 
data size         unlimited 
file size         17179869176b
stack size        unlimited 
file descriptors  64000 
address space     unlimited 
memory above bar  17592186040320m

I do not think node requires as much memory above the bar as listed above but perhaps its  a good starting point and can be scaled back later.

**Comment by Kevchuck** [comment]
So here is what our ulimit is:

core file         8192b
cpu time          unlimited 
data size         unlimited 
file size         unlimited 
stack size        unlimited 
file descriptors  64000 
address space     204800k
memory above bar  2048m

We can't do an unlimited address space, and obviously the memory above the bar that you have is way larger, so can you suggest some starting numbers we can go back to our infrastructure group with and update the profile?

**Comment by mmallick-ca** [comment]
I have been able to reproduce the issue by setting the address space to 200MB. Tried a few different settings and it seems 700MB is sufficient to get to prompt and install a package with npm.

**Comment by mmallick-ca** [comment]
Just want to add that we will be looking into why it requires this much memory. Our port has not really added any new limits and 700MB does seem high for a node application.

**Comment by Kevchuck** [comment]
Awesome.  I'll get this to our infrastructure folks and see about getting a solid gig just to give us some breathing room.  I'll come back and specify the results.

**Comment by Kevchuck** [comment]
Sorry for the late response.  Here is my current ulimit -a settings:

> ulimit -a
core file         8192b
cpu time          unlimited 
data size         unlimited 
file size         unlimited 
stack size        unlimited 
file descriptors  64000 
address space     1000000k
memory above bar  4096m

After setting to that, when running node and node -h everything seems to be working.  Thanks for the help!  I'm going to close this issue, and if we have another, I'll reference this log.
