### ISSUE TITLE
npm install -g loopback-connector-oracle fails on z/OS

### ISSUE THREAD

**Issue by smartmouse** [ibmruntimes/node#81]
:/u/slbld>npm install -g loopback-connector-oracle
npm WARN engine loopback-connector-oracle@3.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.17","npm":"2.15.1"})
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.12.17","npm":"2.15.1"})
/
> loopback-oracle-installer@3.0.0 install /u/slbld/node_global/lib/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer
> node pkginstall.js

_?��%��˚��]��]��]��������?π��ʛ�����������;����?ʚ��/>>?Ȁ��>��_?��%������/Ȁ��>���?>(?��%�^���?%����%�>/_���_?��%��˚������������/Ȁ��>���?>����������?%����_?��%��˚������������/Ȁ|¦���/>?>`_?�˞����%�%�>?��^�%?�/%%��>?��^_?��%��%??��/�,�?>>���?�?�/�%�>?��^_?��%��%??��/�,?�/�%��>��/%%���,��>��/%%�˚����������/Ȁ(?��%�^�?_��%���_?��%��˚�����������/Ȁ|¦���(?��%�^����>��?>��ˀ�_?��%��˚�����������/Ȁ(?��%�%?/���_?��%��˚�����������/Ȁ��>���?>(?��%�^%?/���_?��%��˚�����������/Ȁ��>���?>(?��%���>(/npm ERR! Öâaóùð òôKðð���/Ȁ��/����>?���˚�����������/Ȁ>?���˚������-
npm ERR! argv "/u/slbld/node/bin/node" "/u/slbld/node/bin/npm" "install" "-g" "loopback-connector-oracle"
npm ERR! node v0.12.17
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! loopback-oracle-installer@3.0.0 install: `node pkginstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopback-oracle-installer@3.0.0 install script 'node pkginstall.js'.
npm ERR! This is most likely a problem with the loopback-oracle-installer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pkginstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs loopback-oracle-installer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls loopback-oracle-installer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /u/slbld/npm-debug.log
:/u/slbld>

**Comment by jBarz** [comment]
We are working on fixing up the messed up message. 
To properly interpret the message, here is a workaround

`npm... > output 2>&1`

The output file will have a mix of ebcdic and ascii. The ascii parts will be messed up.

`iconv -f ISO8859-1 -t IBM-1047 output > output.ascii`

Now when you view output.ascii, you will be able to read the ascii parts of the message
In this case the message is as follows:

Error: Cannot find module '.'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at Object.<anonymous> (/u/slbld/oracle/loopback-oracle-installer/pkginstall.js:19:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

I looked into it and it seems that node fails on this line in pkginstall.js from oracle-connecter-installer.

`require.resolve('.');`

I will look into it further

**Comment by jBarz** [comment]
The incoherent error message issue has been fixed. 
Now when you run `npm install -g loopback-connector-oracle`, you will get

> module.js:338
    throw err;
          ^
Error: Cannot find module '.'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at Object.<anonymous> (/u/slbld/oracle/loopback-oracle-installer/pkginstall.js:19:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3


When I run the same command using the latest node v0.12 on linux, i get the same error

> module.js:338
>     throw err;
>           ^
> Error: Cannot find module '.'
>     at Function.Module._resolveFilename (module.js:336:15)
>     at Function.require.resolve (module.js:388:19)
>     at Object.<anonymous> (/home/barboza/node/v0.12/strongloop/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/pkginstall.js:19:32)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Function.Module.runMain (module.js:501:10)
>     at startup (node.js:129:16)
>     at node.js:814:3

So it seem like this module is not compatible with node v0.12.

**Comment by sam-github** [comment]
@bajtos is this expected? Should there be an older version which is compatible with 0.12?

**Comment by bajtos** [comment]
Yes, `loopback-connector-oracle@2` should still support Node v0.10/v0.12.

@raymondfeng and @rashmihunt are most familiar with this particular connector.

**Comment by raymondfeng** [comment]
1. Please note the connector should not be installed globally using `-g`.
2. loopback-connector-oracle@3.x now uses `oracledb` module as the driver. 
3. You'll need to have oracle instant client preinstalled

**Comment by sam-github** [comment]
Thanks you all.

@smartmouse try again with `loopback-connector-oracle@2`.

**Comment by jBarz** [comment]
I tried it myself and got the following error.

Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-os390-s390x-abi14-1.8.0.tar.gz
[Error: Prebuilt tarball not found for your node version and platform: http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-os390-s390x-abi14-1.8.0.tar.gz]

So I guess there needs to be a platform port of the abi?

**Comment by raymondfeng** [comment]
@jBarz Yes for 2.x. Starting from loopback-connector-oracle@3.0, we'll fall back to local compilation of `oracledb`.

Do you have to use Node 0.10/0.12?

**Comment by jBarz** [comment]
We have 0.12 on z/OS for now.
Node v6 will be out middle of next year.

**Comment by raymondfeng** [comment]
@smartmouse Do we still have z/OS access? Maybe we can pre-build the connector there.

**Comment by sam-github** [comment]
Not for 0.12, it isn't worth it. It is end of life in days. If it doesn't work on zOS, that's OK, IMO. Runtimes won't support 0.12 as soon as it is end of life by nodejs upstream.
