### ISSUE TITLE
Node.JS convert UTF8 to EBCDIC in the uploaded file on z/OS

### ISSUE THREAD

**Issue by std3lqi** [ibmruntimes/node#84]
I'm using angula-file-upload and multer to upload binary file to Node.JS on z/OS. The bytes in the uploaded file were converted from UTF-8 to EBCDIC. For example '0x3E' is converted to '0x6E'. 

After having a look at the code, I'm guessing (but not sure before deep investigation) the binary data in POST (form-data) request is converted to EBCDIC by the following code. Appreciate it, if anyone can have a look at it. 

https://github.com/ibmruntimes/node/blob/v0.12-zos/src/node_http_parser.cc

```cc
static void Execute(const FunctionCallbackInfo<Value>& args) {
...
#ifdef __MVS__
    // TODO: (jBarz) consider converting to ebcdic-utf
    __a2e_l(buffer_data, buffer_len);
#endif
```

**Comment by gibfahn** [comment]
cc/ @ibmruntimes/s390

**Comment by jBarz** [comment]
Thanks for the feedback! I am investigating this and will have an update soon.

**Comment by polyrabbit** [comment]
Looking forward to your reply, I'm alse having this issue. Every uploaded binary file is converted in a wrong way.

**Comment by std3lqi** [comment]
After my whole day's investigation, the problem seems related to the node module "multer". It get the correct bytes from Node.JS, but what it outputs to disk is always converted to EBCDIC. 

Here is "node_modules/multer/storage/disk.js".

```
      var finalPath = path.join(destination, filename)
      var outStream = fs.createWriteStream(finalPath)

      file.stream.pipe(outStream)
```

However, no unexpected encoding conversion happened when I used pipe(...) to copy one binary file within Node.JS on z/OS. 

Now I'm confused ...  :-(

**Comment by jBarz** [comment]
@std3lqi : I tested a sample application using "multer" and found that all files written to disk are converted to ebcdic. This works well when you upload an ascii text file (which will be converted to ebcdic on zos). But fails when you upload a binary file.
So I made some [changes ](https://github.com/ibmruntimes/node/commit/dfda95594220551860fd4c264a50c07f59081064)to fix this. 
Note: The file will only be converted to ebcdic if the stream encoding is utf8 or ascii.

**Comment by std3lqi** [comment]
Many thanks, jBarz! 

I suppose the following code should work with those changes, and will be pleased to try it out when new tech preview is ready.

`var outStream = fs.createWriteStream(finalPath, {defaultEncoding:'binary'})`

Thanks, again!

**Comment by jBarz** [comment]
yes, that should work perfectly. But does that code change have to happen in "multer"?
Or in your own application?

**Comment by std3lqi** [comment]
I suppose I should set proper additional encoding-type in angula-file-upload so that "multer" can use correct encoding. So I need find out how later this week.

**Comment by joransiu** [comment]
@std3lqi / @jBarz, cleaning through some old issues.  Based on the last set of comments, it sounds like @jBarz's changes https://github.com/ibmruntimes/node/commit/dfda95594220551860fd4c264a50c07f59081064 should have addressed this encoding issue for binary files?   If you need us to investigate some more, please re-open the issue.  Thanks!
