### ISSUE TITLE
Build of node native addon for z/OS fails due to ordering of command line args to xlC

### ISSUE THREAD

**Issue by zorts** [ibmruntimes/node#85]
I am trying to build a node native addon for z/OS. The `node-gyp build` command fails with these message (just the interesting parts):

    make: Entering directory '/proj/kbm/tsjlc/node.js/node-addon-examples/7_factory_wrap/node_0.12/build'
      CXX(target) Release/obj.target/addon/addon.o
      CXX(target) Release/obj.target/addon/myobject.o
      SOLINK_MODULE(target) Release/obj.target/addon.node
    FSUM3010 Specify a file with the correct suffix (.C, .hh, .i, .c, .i, .s, .o, .x, .p, .I, or .a), or a corresponding data set name, instead of -oRelease/obj.target/addon.node.
    addon.target.mk:129: recipe for target 'Release/obj.target/addon.node' failed
    make: *** [Release/obj.target/addon.node] Error 1
    make: Leaving directory '/proj/kbm/tsjlc/node.js/node-addon-examples/7_factory_wrap/node_0.12/build'

This is a familiar problem to anyone using xlc; it wants all of the command line options with flags **before** the list of files to be processed. The fix is to reorder the command line.

I was able to fix this by changing `node-gyp/addon.gypi`. Here's the diff:

    bash-2.03$ git diff deps/npm/node_modules/node-gyp/addon.gypi
    diff --git a/deps/npm/node_modules/node-gyp/addon.gypi b/deps/npm/node_modules/node-gyp/addon.gypi
    index 9b7f88e..5fa2dfa 100644
    --- a/deps/npm/node_modules/node-gyp/addon.gypi
    +++ b/deps/npm/node_modules/node-gyp/addon.gypi
    @@ -98,6 +98,8 @@
             ],
             'ldflags': [
               '-q64',
    +        ],
    +        'libraries': [
               '<(node_exp_file)'
             ],
           }],
    bash-2.03$ git checkout

See also [this thread on developerworks](https://www.ibm.com/developerworks/community/forums/html/threadTopic?id=d157ffae-4d57-4639-bfe7-b2b5ec4975a4&ps=25).

**Comment by Paul-Ivinson** [comment]
@zorts Can you confirm you have read and understood the Developer's Certificate of Origin in [CONTRIBUTING.md](https://github.com/ibmruntimes/node/blob/v4.x-port/CONTRIBUTING.md#developers-certificate-of-origin-11) and that you are making the requested certification?

**Comment by zorts** [comment]
@Paul-Ivinson Good point. I'm checking, and will get back to you later today.

**Comment by zorts** [comment]
Our legal beagles have confirmed that I may, indeed, make the requested certification. Woot!
