### ISSUE TITLE
Binary files are converted to using an EBCDIC to ASCII converter, breaking image files

### ISSUE THREAD

**Issue by zorts** [ibmruntimes/node#87]
It appears that the z/OS port (ea5) is unconditionally converting files from EBCDIC to ASCII at some point where it shouldn't be. Using express.js, I can serve textual content just fine, but images don't work. If I use iconv to convert the image from iso8859-1 ("ASCII") to ibm-1047 ("EBCDIC"), it works.

The directory I'm running in looks like this:

    bash-2.03$ ls -lT index.html simple.js Z13*
    - untagged    T=off -rw-r--r--   1 TSJLC    KBMUSER    20382 Feb 27 11:49 Z13.png
    - untagged    T=off -rw-r--r--   1 TSJLC    KBMUSER    20382 Feb 27 11:50 Z13e.png
    - untagged    T=off -rw-r--r--   1 TSJLC    KBMUSER       84 Feb 27 11:46 index.html
    - untagged    T=off -rw-r--r--   1 TSJLC    KBMUSER      363 Feb 27 13:26 simple.js
    bash-2.03$

The server code (simple.js) is:

    'use strict';
    const port=32688;
    const express = require('express');
    var app = express();
    app.use("/", express.static("."));
    app.use(function (req, res, next) {
      console.log(req.url+": unknown resource requested");
    })

    const http = require('http');
    var server = http.Server(app);

    server.listen(port, function(){
      console.log('listening on port '+port);
    });

I am running with _BPXK_AUTOCVT=OFF; I've tried setting _BPXK_AUTOCVT=ON and then tagging the files as binary, but the behavior doesn't change.

Is this a known problem or am I doing something wrong?

-- Jerry

**Comment by jBarz** [comment]
Hi Jerry,
You are right. The files are unconditionally being converted which is something we should fix.
In the meanwhile, to get images working with ea5, you could try tagging the image files as ASCII text and then turning on _BPXK_AUTOCVT. 

e.g.
_chtag -tc ISO8859-1 image_file_
_ls -T image_file_
t ISO8859-1   T=on  image_file

**Comment by zorts** [comment]
Tagging the images as ASCII worked. However, this is obviously not a long term solution. 

Do you plan to use enhanced ASCII at some point in the future? That would also eliminate the need to hack all the internal string constants to hex.

**Comment by mmallick-ca** [comment]
Just a quick note about the use of enhanced ASCII. Initially we did think about using the Enhanced ASCII facility. However with enhanced ASCII a **subset**  of C headers and functions are supported. Given that both v8 and Node are quite active projects, we decided not to use the facility given this limitation.

**Comment by zorts** [comment]
It's a very LARGE subset! FWIW - we (Rocket Software) have been using enhanced ASCII to port open source tools to z/OS (including the recent git port) with good results; I can't recall encountering a function that wasn't supported. 

That said - even without using enhanced ASCII, it's possible to examine the file tag to determine encoding and take action based on that. I'm currently looking at the node/v8/uv source to see how hard that would be.

**Comment by std3lqi** [comment]
I have the same problem with images, and tag them as work-around.

**Comment by jBarz** [comment]
With the latest beta, merely tagging files as binary should be sufficient.
You can download v6.11.0 Beta2 here.
https://developer.ibm.com/node/sdk/ztp/

I will close this issue for now but please feel free to re-open if necessary.
