### ISSUE TITLE
S0C1

### ISSUE THREAD

**Issue by gatogatogato** [ibmruntimes/node#88]
After downloading/unpacking into my USS I always run into an S0C1

CEE3201S The system detected an operation exception (System Completion Code=0C1).
         From entry point v8::base::OS::Abort() at compile unit offset +0000000000000000 at entry offset -000000001775D9A0 at address 0000000000000000.
         Possible Bad Branch:  Statement: 344  Offset: +00000042

ulimit -a gives me this:

```
core file         8192b
cpu time          1000
data size         unlimited
file size         unlimited
stack size        unlimited
file descriptors  65535
address space     200000k
memory above bar  2000m
```

We have z/OS 2.2 at a very current maintenance level.

**Comment by mmallick-ca** [comment]
Could you try bumping up the address space setting to 700MB and giving it a try? Without the full traceback its hard to tell but we have encountered a similar SOC1 when the address space was limited to less than 700MB.

**Comment by gatogatogato** [comment]
Thanks for your reply.
`ulimit -A 700000`
just returns a
`ulimit: FSUM9222 set limit failed: EDC5121I Invalid argument.`

**Comment by rich335z** [comment]
@gatogatogato the ability to set address space size is commonly restricted to privileged sysadmin roles. You may need to request this size increase from another team in your org.

**Comment by gatogatogato** [comment]
@rich335z In my OMVS segment I have ASSIZE(800,000,000) (ACF2) but maybe we have other limiting factors in place.

**Comment by rich335z** [comment]
@gatogatogato Sorry, I had to rely on my InfoSec team to make this change for me, and I'm not sure what they changed... I do know that the first change they made didn't provide the expected increase, and they had to go back and change something else... maybe MEMLIMIT?

**Comment by jguillaumes** [comment]
Hello. 
We are also getting a S0C1 trying to run npm:

```
CEE3201S The system detected an operation exception (System Completion Code=0C1)
.                                                                               
         From compile unit TLBA99ME:/home/jenkins/workspace/ibmnode-6.x-build-zo
s/node/deps/v8z/src/parsing/expression-classifier.h at entry point _ZN2v88intern
al20ExpressionClassifierINS0_12ParserTraitsEE25RecordBindingPatternErrorERKNS0..
. at                                                                            
         statement 221 at compile unit offset +000000003DD8389C at entry offset 
+0000000000000044 at address 000000003DD8389C.                                  
````

We are above 700M of memory:

```
> ulimit -A         
928000                                
```

I'm trying it in a 2817 machine, with current z/OS 2.2.

**Comment by jBarz** [comment]
hi @jguillaumes

Is this with using the latest node v6.10.3 beta?
What is the npm command you are using?

**Comment by jguillaumes** [comment]
Yes, the just released beta. And the command is simply

```
npm --version
```

**Comment by mmallick-ca** [comment]
Hi @jguillaumes 

Is there a CEEDUMP.* traceback file generated with this error? If there is one could you share it with us? Just out of curiosity are you atleast able to invoke node and interact with the prompt?
Based on the error message I do not think this SOC1 is memory related, if anything its related to parsing the javascript(potentially the npm source file).

It maybe worthwhile to take a quick look at the npm source in the bin folder  of your installation directory to make sure that the file did not get corrupted(just a hunch).

Thanks

**Comment by jguillaumes** [comment]
Hi @mmallick-ca,

I'll try to generate a CEEDUMP tomorrow and I have no problem sharing it with you. How should I send you the file? An attachment here is OK?

As for the npm, I have changed its first line (the #! one) because I have installed the beta in my home directory instead than under /usr/local. By the way, executing it without parameters (just ```npm```) it generates the same ABEND.

Before you ask, I have exported STEPLIB pointing to the SCEERUN2 library that comes with the compiler bundled with the beta.

**Comment by mmallick-ca** [comment]
Yup, posting it here should be fine and just to confirm you are running on z196 machine right?

**Comment by jguillaumes** [comment]
I'm attaching the CEEDUMP
[ceedump.txt](https://github.com/ibmruntimes/node/files/1067805/ceedump.txt)

**Comment by mmallick-ca** [comment]
Hi @jguillaumes 

Looking at the traceback it seems we hit the SOC1 very early, during the bootstrap. We have not run into this during testing, we are going to investigate further by trying to run the beta on a z196 machine and see if we are able to reproduce the issue. In that case it might be something to do with our build process and we would need to review it to see whats going on.

Apologies for the trouble, hope to update you soon.

**Comment by jguillaumes** [comment]
No problem, I'll be watching this space :)
Just FYI, the system I'm doing the tests is a z12.

**Comment by jBarz** [comment]
@jguillaumes, by z12 do you mean zEC12?
Your earlier comment was about testing on a z196 system. (2817 maps to z196 hardware)

> I'm trying it in a 2817 machine, with current z/OS 2.2.

**Comment by jguillaumes** [comment]
Oh, sorry for the confusion. What I wanted to mean was "z196 or superior". At that time I didn't know for sure which was the specific architecture of the test machine (the operation guys can IPL it in different CECs), but was sure it was >= z196.

**Comment by jBarz** [comment]
@jguillaumes Can you try the beta2 which is now available for download?
https://developer.ibm.com/node/sdk/ztp/

**Comment by jBarz** [comment]
Please re-open the issue if it persists after beta2.
