### ISSUE TITLE
Errors running unpack.pl

### ISSUE THREAD

**Issue by rich335z** [ibmruntimes/node#89]
Receiving the following error when running the unpack.pl script during install of v6.10.3 beta for z/OS:

```
./unpack.pl: line 1: unexpected EOF while looking for matching ``'
./unpack.pl: line 2: syntax error: unexpected end of file
```

**Comment by rich335z** [comment]
Resolved this issue with two actions:

Update the shebang to point at local perl installation - I have perl installed in my home directory, so I had to update the shebang reference

Remove tagging of `unpack.pl` with `chtag -r ./unpack.pl` - My profile has _BPXK_AUTOCVT=ON and _CEE_RUNOPTS="FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)" as required by the z/OS Git client. The unpack.pl came out tagged (or auto-tagged) as ISO8859-1. I had to remove the tagging for the script to execute.

**Comment by rich335z** [comment]
However, the script will still not run successfully. It fails when copying the files to the MVS datasets. Initially, I noticed the HLQ (which I allowed to default) was passing through in lower case on the DSNs:

```
<DEB> unloading /u/rjack11/node-v6.10.3-os390-s390x/bin/xmits/USRHLQ.CEEZ230.D170510.RT22.SCEERUN.XMIT into rjack11.CEEZ230.D170510.RT22.SCEERUN
An error occurred while receiving temporary dataset rjack11.TMP.T8523930.T6845663.P7641695 to dataset rjack11.CEEZ230.D170510.RT22.SCEERUN. at ./unpack.pl line 147.
cannot receive /u/rjack11/node-v6.10.3-os390-s390x/bin/xmits/USRHLQ.CEEZ230.D170510.RT22.SCEERUN.XMIT to rjack11.CEEZ230.D170510.RT22.SCEERUN at ./unpack.pl line 61.
```

So, I explicitly set the HLQ in upper case via the `export COMPILER_INSTALL_HLQ=`

Cleaned up with the `unpack.pl -uninstall`, and re-ran the install, and it fails at the same point. Noticed that the submitted jobs are failing with JCL errors due to lower case characters:

```
//rjack11A JOB (157A,2326),'RECEIVE',MSGLEVEL=(1,1),MSGCLASS=A,
//  CLASS=A,REGION=0M,USER=rjack11                             
//REC     EXEC PGM=IKJEFT01,DYNAMNBR=3000                      
//SYSTSPRT DD SYSOUT=*                                         
//SYSPRINT DD SYSOUT=*                                         
//SYSTSIN DD DATA,DLM='!!'                                     
 RECEIVE +                                                     
 INDATASET('RJACK11.TMP.T8524499.T7175024.P3004829')           
 DATASET('RJACK11.CEEZ230.D170510.RT22.SCEERUN')               
!!                                                             
//                                                             
```

It appears that `$user` in the script is not getting set to upper case. So, I added a statement to set a new variable as upper case `my $user1 = uc $user;` and included the `$user1` variable in JCL string builders. This allowed _a_ job to run successfully and copy files into the SCEERUN dataset:

```
READY                                                                           
 RECEIVE INDATASET('RJACK11.TMP.T8525898.T7175310.F6242997')                    
Dataset TSCTEST.CEEZ230.D170510.RT22.SCEERUN from TSC390 on TOROLABA            
Enter restore parameters or 'DELETE' or 'END' +                                 
The input file attributes are: DSORG=PARTITIONED, RECFM=U, BLKSIZE=32760, LRECL=
You may enter DSNAME, SPACE, UNIT, VOL, OLD/NEW, or RESTORE/COPY/DELETE/END     
Restore successful to dataset 'RJACK11.CEEZ230.D170510.RT22.SCEERUN'            
READY                                                                           
END                                                                             
```

However, the script still fails at this point, apparently not recognizing that the job completed successfully:

```
<DEB> unloading /u/rjack11/node-v6.10.3-os390-s390x/bin/xmits/USRHLQ.CEEZ230.D170510.RT22.SCEERUN.XMIT into RJACK11.CEEZ230.D170510.RT22.SCEERUN
An error occurred while receiving temporary dataset RJACK11.TMP.T8526747.T0398526.T2118263 to dataset RJACK11.CEEZ230.D170510.RT22.SCEERUN. at ./unpack.pl line 148.
cannot receive /u/rjack11/node-v6.10.3-os390-s390x/bin/xmits/USRHLQ.CEEZ230.D170510.RT22.SCEERUN.XMIT to RJACK11.CEEZ230.D170510.RT22.SCEERUN at ./unpack.pl line 62
```

I'm not sure where to go from here. Please advise.

**Comment by stevench2000** [comment]
Thanks for the feed back.
We will look into the other issues.
For the last issue about unloading the datasets, we check the HELD output queue in SDSF to determine whether the job has completed successful:
1. The issue you are seeing might be that the MSGCLASS A in the JCL doesn’t save the job output to HELD output queue in SDSF. Just wondering, do you see the receive jobs from the HELD output queue?
2. If the receive jobs are successful and we want to bypass the checking in the HELD output queue, we can change this line in the unpack.pl script:
```return 0 if (CheckHeldOutput::check_held_output(\@jcl_output) != 0);```
to
```return 1;```
and since mostly we will want the samething for the job to delete dataset as well, so we will need to also change this line:
```return (CheckHeldOutput::check_held_output(\@held_output) == 0);```
to
```return 1;```
Hope this helps.

**Comment by rich335z** [comment]
Thanks... I routed to the held queue and that got me past this issue. The script now fails with:
```
<DEB> unloading /u/rjack11/node-v6.10.3-os390-s390x/bin/xmits/USRHLQ.CEEZ230.D170510.RT22.SCEERUN2.XMIT into RJACK11.CEEZ230.D170510.RT22.SCEERUN2
cp: FSUM6258 cannot open file "//'RJACK11.TMP.T8624199.T3622307.D1289967'": EDC5061I An error occurred when attempting to define a file to the system.
An error occurred while copying file /u/rjack11/node-v6.10.3-os390-s390x/bin/xmits/USRHLQ.CEEZ230.D170510.RT22.SCEERUN2.XMIT to dataset RJACK11.TMP.T8624199.T3622307.D1289967. --  at ./unpack.pl line 144.
cannot receive /u/rjack11/node-v6.10.3-os390-s390x/bin/xmits/USRHLQ.CEEZ230.D170510.RT22.SCEERUN2.XMIT to RJACK11.CEEZ230.D170510.RT22.SCEERUN2 at ./unpack.pl line 62.
```

I removed bash as my login shell and enabled _BPX_SHAREAS and _BPX_SPAWN_SCRIPT, which don't appear to be honored as I still see multiple asids being spawned.

**Comment by stevench2000** [comment]
Thanks again for the feed back.
Just wondering what zOS version is the system currently running on? It might be related to this APAR:
http://www-01.ibm.com/support/docview.wss?uid=isg1OA44122
Also, the datasets when unloaded on MVS require approximately 2 GB of space, so please ensure the system has more available space on the volumes.
Hope this helps.

**Comment by rich335z** [comment]
Thanks for the info. We are on z/OS 2.2 in this system, though.

Good point on the disk space... the descriptiveness of that EDC5061I message leaves a lot to be desired, but it appears to be most commonly associated with contention. So, that's where my head was at.

We have ACS restrictions in place on TSO user dataset space requests. Basically, any request for greater than (CYL,(50,50)) on a TSO user dataset is failed by the system. The `unpack.pl` script does a `cp` to the <userid>.TMP datasets regardless of the COMPILER_INSTALL_HLQ value, and some of those `cp` commands request space > (CYL,(50,50)).

I modified `getNumCyls` to reduce `$num_cyls` to 50 if happened to get calculated as > 50. and got the script to run and finish the install successfully.

A couple points of note:

The `unpack.pl -uninstall` apparently removes the bin dir (and subsequently the node file), so if using it for clean-up of the compiler stuff, we'll have to re-extract /bin

Also, I'm getting the same EOF syntax error (as mentioned originally in this thread) on npm commands. I suspect it's the file tagging... I'll investigate and follow up on a different issue if necessary.

Thanks again,
Rich

**Comment by daveyc** [comment]
We're having the same problem. It seems to me that the jobstep parsing in `CheckHeldOutput::check_held_output` is not reliable. Of course the format depends on the IEFACTRT exit. We use [Rob Scotts popular routine](http://planetmvs.com/flowerbox/RobScott.txt). You should investigate the `IEF142I` message in the JESYSMSG file if you want to reliably yank step condition codes.

**Comment by jBarz** [comment]
If this issue no longer needs to be open, I will close it this week. If you are still seeing this issue, do let us know.

**Comment by likepunk** [comment]
We have the same issue - can't pass unpack.pl 
`
:JCRUZ:/RPRT/zoe/nodejs/node-v6.14.3-os390-s390x:Ready set | grep MSG    
COMPILER_INSTALL_HELD_MSGCLASS="S"                                       
:JCRUZ:/RPRT/zoe/nodejs/node-v6.14.3-os390-s390x:Ready                   
 
./unpack 
IGD01007I DC: TEMP DATASET        
                                  
IGD01008I SC: TEMP DATASET        
                                  
IGD01007I DC: TEMP DATASET        
                                  
IGD01008I SC: TEMP DATASET        
                                  
IGD01007I DC: TEMP DATASET        
                                  
IGD01008I SC: TEMP DATASET        
 
Fails at this point in Perl script
                                 
An error occurred while receiving temporary dataset JCRUZ.TMP.T9023359.T3623170.
E5287688 to dataset JCRUZ.ZOSV221.D170810.BINDER.LOAD. at ./unpack.pl line 153. 
<ERR> cannot receive /RPRT/zoe/nodejs/node-v6.14.3-os390-s390x/bin/xmits/USRHLQ.
ZOSV221.D170810.BINDER.LOAD.XMIT to JCRUZ.ZOSV221.D170810.BINDER.LOAD at ./unpac
k.pl line 62.                                                                   
:JCRUZ:/RPRT/zoe/nodejs/node-v6.14.3-os390-s390x:Ready :JCRUZ:/RPRT/zoe/nodejs/n
ode-v6.14.3-os390-s390x:Ready :JCRUZ:/RPRT/zoe/nodejs/node-v6.14.3-os390-s390x:R
While in function
000143 sub receiveDSfromFile {                                                 
000144   my ($file, $dataset) = @_;                                            
000145                                                                         
000146   my $tempDS = getTempDSName();                                         
000147                                                                         
000148   if (! copyFileToSequentialDS($file, $tempDS)) {                       
000149     warn "An error occurred while copying file $file to dataset $tempDS.
000150     return 0;                                                           
000151   }                                                                     
000152   if (! receiveDSfromDS($tempDS, $dataset)) {                           
000153     warn "An error occurred while receiving temporary dataset $tempDS to
000154     return 0;                                                           
000155   }                                                                     
000156   if (! deleteDS($tempDS)) {                                            
000157     warn "An error occurred when deleting $tempDS.";                    
000158     return 0;                                                           
000159   }                                                                     
000160                                                                         
000161   return 1;                                                             
eady 
We believe that the CheckHeldOutput method is not parsing split job output listing correctly.
 my @jcl_output = SafeSubmit::submit_jcl(@receive_jcl);                
 return 0 if (CheckHeldOutput::check_held_output(\@jcl_output) != 0);  
When we view listing from SDSF we notice that two instances of the job output listing
 SDSF OUTPUT ALL CLASSES ALL FORMS    LINES 86           DATA SET DISPLAYED     
 COMMAND INPUT ===>                                            SCROLL ===> PAGE 
 NP   JOBNAME  JobID    Owner    Prty C Forms    Dest                 Tot-Rec   
      JCRUZA   JOB08064 JCRUZ     144 S STD      LOCAL                     51   
      JCRUZA   JOB08064 JCRUZ     144 S STD      LOCAL                     10           
Contains TSO command output
 SDSF OUTPUT DISPLAY JCRUZA   JOB08064  DSID   104 LINE 0       COLUMNS 02- 81  
 COMMAND INPUT ===>                                            SCROLL ===> PAGE 
********************************* TOP OF DATA **********************************
                                         IEBCOPY MESSAGES AND CONTROL STATEMENTS
IEB1135I IEBCOPY  FMID HDZ2230  SERVICE LEVEL UA92265  DATED 20170618 DFSMS 02.0
IEB1035I JCRUZA    REC      14:29:36 MON 08 OCT 2018 PARM=''                    
 COPY INDD=((SYS00004,R)),OUTDD=SYS00003                                        
IEB1013I COPYING FROM PDSU  INDD=SYS00004 VOL=WORK02 DSN=SYS18281.T142935.RA000.
IEB1014I           TO PDSE OUTDD=SYS00003 VOL=SMF002 DSN=JCRUZ.ZOSV221.D170810.B
IGW01551I MEMBER AMBLIST  HAS BEEN LOADED                                       
IGW01553I ALIAS HEWL  OF COPIED PRIMARY IEWBLINK HAS BEEN LOADED                
IGW01551I MEMBER HEWLD  HAS BEEN LOADED                                         
IGW01553I ALIAS HEWLDI  OF COPIED PRIMARY HEWLD  HAS BEEN LOADED                
IGW01551I MEMBER HEWLDIA  HAS BEEN LOADED                                       
IGW01551I MEMBER IEWTPORT HAS BEEN LOADED                                       
IGW01551I MEMBER IGWSPZAP HAS BEEN LOADED                                       
IGW01553I ALIAS IMBLIST  OF COPIED PRIMARY AMBLIST  HAS BEEN LOADED             
IGW01553I ALIAS LINKEDIT OF COPIED PRIMARY IEWBLINK HAS BEEN LOADED             
IGW01553I ALIAS LOADER  OF COPIED PRIMARY IEWBLINK HAS BEEN LOADED              
IGW01550I 43 OF 43  MEMBERS WERE LOADED                                         
IEB147I END OF JOB - 0 WAS HIGHEST SEVERITY CODE        
Contains MVS messages
 SDSF OUTPUT DISPLAY JCRUZA   JOB08064  DSID   102 LINE 0       COLUMNS 02- 81  
 COMMAND INPUT ===>                                            SCROLL ===> PAGE 
********************************* TOP OF DATA **********************************
READY                                                                           
 RECEIVE INDATASET('JCRUZ.TMP.T9023359.T3623170.E5287688')                      
INMR901I Dataset TSCTEST.ZOSV221.D170810.BINDER.LOAD from TSC390 on TOROLABA    
INMR154I The incoming data set is a 'PROGRAM LIBRARY'.                          
INMR906A Enter restore parameters or 'DELETE' or 'END' +                        
INMR908A The input file attributes are: DSORG=PARTITIONED, RECFM=U, BLKSIZE=6144
INMR909A You may enter DSNAME, SPACE, UNIT, VOL, OLD/NEW, or RESTORE/COPY/DELETE
INMR001I Restore successful to dataset 'JCRUZ.ZOSV221.D170810.BINDER.LOAD'      
READY                                                                           
END                                                                             READY                                                                                      
Both output listing contain a zero return code
`

**Comment by joransiu** [comment]
Hi @likepunk :  Can you try `export COMPILER_INSTALL_MSGCLASS="S"` instead and see if it resolves your issue?   We had inadvertently introduced an incorrect change to the documentation for that environment variable, and fixed the documentation last week.

/cc @stevench2000

**Comment by likepunk** [comment]
Thanks @joransiu , but we got the same results again even with the export set. Any other suggestions/recommendations?

**Comment by joransiu** [comment]
We had a web ex session with @likepunk and team.  The issue was that the `sed` tool that the script uses picked up the version that came with Rocket's python.   We'll update the `unpack.pl` tool to explicitly use `/bin/sed`.  With that, @likepunk was able to install Node.js successfully.

**Comment by yugeshpothuru** [comment]
Hi,
we are running zOS 2.2 and I'm trying to install the node.js and run the unpack.pl but it is failing as below.

I have checked the module CELHDCPP for the string get_new_handler__3stdFv I don't see it in my zOS 2.2 but when I check a 2.3 system I to see it. 

Can someone help me to bypass this or modify the unpack.pl to run on zOS 2.2?

<DEB> processing file /S0W1/var/zowe/zowerun/nodejs/bin/xlclang                 
<DEB> processing file /S0W1/var/zowe/zowerun/nodejs/bin/xlclang++               
<INFO> running : /S0W1/var/zowe/zowerun/nodejs/bin/njsc++ ._temp.hello.cpp -o he
llo -qphaseid && /S0W1/var/zowe/zowerun/nodejs/bin/run ./hello && rm -f ._temp.h
ello.cpp hello!                                                                 
CNJ0000(I) Product(5655-SDK) Phase(CNJEOPTP) Level(D170803.N106)                
CNJ0000(I) Product(5655-SDK) Phase(CNJDRVR ) Level(D170803.N106)                
CEE3561S External function get_new_handler__3stdFv was not found in DLL CELHDCPP
.                                                                               
         From entry point std::set_new_handler(void (*)()) at statement 181 at c
ompile unit offset +00000062 at entry                                           
         offset +00000062 at address 24CC66CA.                                  
FSUM3224 njsc++: Fatal error in /S0W1/var/zowe/zowerun/nodejs/bin/util/usr/lpp/I
BM/cnj/njsc/exe/cnjdrvr: signal 9 received.                                     
fail to verify installation at ./unpack.pl line 81.
