### ISSUE TITLE
node 'killed' when I try to run the example.js web server example

### ISSUE THREAD

**Issue by ghost** [ibmruntimes/node#92]
I had a successful installation as far as I can tell, but when I run the sample program:

it is killed. Looking in the JES log, I see:
+CEE3798I ATTEMPTING TO TAKE A DUMP FOR ABEND U4087 TO DATA SET:         
IBMUSER.D207.T1627305.P4010044                                           
IGD100I 0AA3 ALLOCATED TO DDNAME SYS00003 DATACLAS (        )            
IEA822I COMPLETE TRANSACTION DUMP WRITTEN TO IBMUSER.D207.T1627305.P4010 
044                                                                      
+CEE3797I LANGUAGE ENVIRONMENT HAS DYNAMICALLY CREATED A DUMP.           
+CEE0374C CONDITION=CEE3561S TOKEN=00030DE9 59C3C5C5 00000000_00000001   
902                                                                      
          WHILE RUNNING PROGRAM _ZN2v88interna WHICH STARTS AT 205F1058  
          AT THE TIME OF INTERRUPT                                       
          PSW     00000001 80000000 00000000_22B3E7F2                    
          GPR 0-2 BBBBBBBB_BBBBBBBB BBBBBBBB_BBBBBBBB BBBBBBBB_BBBBBBBB  
          GPR 3-5 BBBBBBBB_BBBBBBBB 00000050_082F3CE8 00000000_22B3E0D8  
          GPR 6-8 00000000_22B3DBB0 00000000_22B3E7F2 00000050_00108398  
          GPR 9-B 00000050_082F4AE0 00000050_082F4AE0 00000050_082F4B00  
          GPR C-E 00000000_00000007 00000000_2306A130 00000000_00000000  
          GPR F   00000000_22E37644                                      
+CEE0374C CONDITION=CEE5702S TOKEN=00031646 59C3C5C5 00000000_00000000   
903                                                                      
          WHILE RUNNING PROGRAM CEEHSGLT WHICH STARTS AT 22B3E788        
          AT THE TIME OF INTERRUPT                                       
          PSW     00000001 80000000 00000000_22B3E7F2                    
          GPR 0-2 BBBBBBBB_BBBBBBBB BBBBBBBB_BBBBBBBB BBBBBBBB_BBBBBBBB  
          GPR 3-5 BBBBBBBB_BBBBBBBB 00000050_082EB108 00000000_22B3E0D8  
          GPR 6-8 00000000_22B3DBB0 00000000_22B3E7F2 00000050_00108398  
          GPR 9-B 00000050_082EBE20 00000000_00000000 00000050_08AF3370  
          GPR C-E 00000050_00108398 00000000_2306A130 00000050_08AF3370  
          GPR F   00000000_00000000                                      
IEA989I SLIP TRAP ID=X422 MATCHED.  JOBNAME=IBMUSER2, ASID=0059.         
IEA989I SLIP TRAP ID=X422 MATCHED.  JOBNAME=IBMUSER2, ASID=0059.         
IEA989I SLIP TRAP ID=X422 MATCHED.  JOBNAME=IBMUSER2, ASID=0059.         
IEA989I SLIP TRAP ID=X422 MATCHED.  JOBNAME/ASID NOT AVAILABLE.          
IEA989I SLIP TRAP ID=X422 MATCHED.  JOBNAME/ASID NOT AVAILABLE.          

Not sure if others have seen this as well... I have installed perl from Rocket and installed the PTF referenced for z/OS 2.2

**Comment by ghost** [comment]
I think I answered my own question. If I STEPLIB in the SCEERUN2, it seems to work, so perhaps I haven't installed the PTF after all...

**Comment by mmallick-ca** [comment]
Hey Mike, I believe your installation has probably been successful the installer(unpack.pl) installs all the datasets under the users HLQ by default and hence you have to explicitly set your STEPLIB to pick it up during execution. The blogpost below has more details about getting started with the beta.

https://developer.ibm.com/node/2017/07/12/getting-started-node-js-beta-zos/

**Comment by ghost** [comment]
Thanks mmallick-ca. As it turns out, not being a systems programmer, I had forgot to do:
/F LLA,REFRESH
to refresh SCEERUN2 dataset after installing the PTF.
Once I did that, I no longer needed the STEPLIB!
