### ISSUE TITLE
z/OS: V8 heap obtained from 31-bit MVS storage

### ISSUE THREAD

**Issue by matthewpwilson** [ibmruntimes/node#93]
The V8 heap is allocated from 31-bit virtual storage. Due to the large size of the initial allocation, this means that the number of node instances that can be run concurrently in a single address space are severely limited.  Allocating the heap from 64-bit storage would remove this limitation.

In addition, the heap storage does not seem to be freed if the node process exits prematurely (e.g. if the app uses `process.exit()` ).   Storage remains allocated until the address space terminates.  One way to avoid this would be to allocate the heap via LE. 

@mmallick-ca

**Comment by mmallick-ca** [comment]
We are working on adding support to allow the v8 heap to be allocate above the bar. We intend to use moservices to request/release this memory and hope to have a test driver/PTF available at the end of this month. To be able to use the memory above the bar the user will need to be on z/OS 2.3.

**Comment by matthewpwilson** [comment]
We've tested the fix as supplied in 6.14.2 and can confirm we can see the heap storage being allocated in 64-bit storage with z/OS 2.3. Also on z/OS 2.2 we see dramatically smaller 31-bit storage requirements. A great improvement, thanks.
