### ISSUE TITLE
worker threads not terminated cleanly on z/OS

### ISSUE THREAD

**Issue by matthewpwilson** [ibmruntimes/node#96]
Running an app that makes HTTP requests, when the node process terminates several threads terminate without being undubbed. These appear to be libuv worker threads with the following stack:
1        CEEOPCW     +00000000              CELQLIB     
2        pthread_cond_wait                              
                     +000001EE              CELQLIB     
3        pthread_cond_wait_03                           
                     +00000018              CELQLIB     
4        @@WRAP@TRACE+000001AE              CELQLIB     
5        uv_cond_wait+0000001C              *PATHNAM    
6        worker      +00000058              *PATHNAM    
7        CELQPCMM    +00000F80              CELQLIB     

This can lead to A03 abends when the process terminates, and storage not being released properly.

**Comment by jBarz** [comment]
Provided @matthewpwilson with experimental binary.

**Comment by matthewpwilson** [comment]
Unfortunately we're still seeing this issue.

**Comment by gireeshpunathil** [comment]
should the main thread explicitly issue `pthread_quiesce` on workers before exiting itself? @jBarz

**Comment by jBarz** [comment]
@gireeshpunathil Thanks for that suggestion.
z/OS indeed provides a pthread_quiesce call which can do the following:
`Terminates all threads (except the invoking thread) that were created with pthread_create and IPT threads, allowing the signal interface routine to receive control when the quiesce request is delivered.`

However, I provided a binary to @matthewpwilson with that call being invoked when node exits,  but for some reason, the threads are not terminated. Let me investigate further.

**Comment by matthewpwilson** [comment]
I can confirm this issue is resolved with a fix provided by @jBarz

**Comment by jBarz** [comment]
The upcoming PTF for February will have this fix. I will update this issue when it is released officially.

**Comment by jBarz** [comment]
Resolved in v6.13.1.0 available here https://developer.ibm.com/node/sdk/ztp/
